#ifdef SPANISH
	#define STR0001 "Operador no registrado"
	#define STR0002 "Aviso"
	#define STR0003 "Inventario"
	#define STR0004 "Codigo Maestro"
	#define STR0005 "Almacen "
	#define STR0006 "Ubicacion"
	#define STR0007 "Cantidad"
	#define STR0008 "Etiqueta"
	#define STR0009 "Producto"
	#define STR0010 "¿Desea finalizar el conteo?"
	#define STR0011 "Falla en la grabacion del inventario"
	#define STR0012 "ERROR"
	#define STR0013 "Inventario concluido"
	#define STR0014 "No se alcanzo el numero necesario de conteos solicitados"
	#define STR0015 "Inv. en curso"
	#define STR0016 "Codigo maestro de inventario no registrado"
	#define STR0017 "Atencion"
	#define STR0018 "Inventario finalizado"
	#define STR0019 "Operador ejecutando inventario en otro terminal"
	#define STR0020 "Etiqueta no valida"
	#define STR0021 "Aviso"
	#define STR0022 "Deposito y ubicacion incorrectos."
	#define STR0023 "Lo correcto seria:"
	#define STR0024 "Ubicacion no registrada."
	#define STR0025 "Producto pertenece a la ubicacion:"
	#define STR0026 "Codigo ya leido"
	#define STR0027 "Lectura no valida"
	#define STR0028 "Etiqueta no valida."
	#define STR0029 "íEtiqueta no valida!"
	#define STR0030 "Producto no registrado."
	#define STR0031 "Producto diferente del que debe ser inventariado."
	#define STR0032 "Espere..."
	#define STR0033 "Ningun producto fue inventariado, confirma stock Cero"
	#define STR0034 "Configure os parametros MV_VLDTINV e MV_INVAUT"
	#define STR0035 "Va para el Almacen "
	#define STR0036 " Direccion "
	#define STR0037 "Producto sin direccion"
	#define STR0038 "Inventario"
	#define STR0039 "Selecione:"
	#define STR0040 "Mestre"
	#define STR0041 "Endereco"
	#define STR0042 "Necessario ativar o parametro MV_CBPE012"
	#define STR0043 "Informacao"
	#define STR0044 "Leia a Etiqueta de"
	#define STR0045 "Produto p/ localizar"
	#define STR0046 "mestre de inventario"
	#define STR0047 "Armazem"
	#define STR0048 "Endereco p/ localizar"
	#define STR0049 "Nao existem Produtos para este endereco. A contagem nao sera finalizada!"
	#define STR0050 "-->Mestre:"
	#define STR0051 " - Erro na rotina automatica"
	#define STR0052 "Mestre "
	#define STR0053 " foi finalizado com sucesso"
	#define STR0054 "--> Mestre: "
	#define STR0055 " - Nao foi finalizado"
	#define STR0056 "- Contagem divergente"
	#define STR0057 "- Inventario bloqueado para auditoria"
	#define STR0058 "Inventario bloqueado para Auditoria"
	#define STR0059 "Operador ja realizou contagem para o inventario"
	#define STR0060 "Sem permissao"
	#define STR0061 "Somente o Operador "
	#define STR0062 " pode dar continuidade a este inventario"
	#define STR0063 "Contagens == 1"
	#define STR0064 ", produto pertence a um pallet "
	#define STR0065 "Produto nao localizado na tabela de saldos fisicos(SB2)."
	#define STR0066 'Produto nao pertence a(s) classe(s) "'
	#define STR0067 '" da curva ABC!'
	#define STR0068 "Etiqueta de produto sem endereco"
	#define STR0069 "Produto sem controle de endereco"
	#define STR0070 "Produto com "
	#define STR0071 "Qtde variavel"
	#define STR0072 "Quantidade Invalida"
	#define STR0073 "Nao eh necessario a recontagem!!!"
	#define STR0074 "Produto ja auditado"
	#define STR0075 " Nao encontrado"
	#define STR0076 "atribuicao simbolica somente para nao validar a contagem"
	#define STR0077 "Incluindo Inventario"
	#define STR0078 "Erro na rotina automatica:"
	#define STR0079 "Produto: "
	#define STR0080 "Armazem: "
	#define STR0081 "Endereco:"
	#define STR0082 "Lote:    "
	#define STR0083 "Sub-Lote:"
	#define STR0084 "N.Serie: "
	#define STR0085 'Erro na rotina automatica, necessario excluir esta finalizacao pelo Mestre de Inventario'
	#define STR0086 "Acerto Estoque..."
	#define STR0087 "nao deve entrar"
	#define STR0088 "Etiqueta Invalida"
	#define STR0089 "Nao Iniciado"
	#define STR0090 "Em Andamento"
	#define STR0091 "Mestre de Inventario nao encontrado"
	#define STR0092 "Data"
	#define STR0093 "Status"
	#define STR0094 "Mestre de Inventario nao selecionado"
	#define STR0095 "Lote"
	#define STR0096 "SubLote"
	#define STR0097 "Serie"
	#define STR0098 "Produto nao localizado na tabela de demandas (SB3)!"
	#define STR0099 "Favor executar o recalculo do lote economico para atualizar a tabela de demandas!"
	#define STR0100 "Nao existem produtos para este endereco nos saldos do sistema, "
	#define STR0101 "nem foi detectada a ocorrencia de inventario para este mestre!"
	#define STR0102 "Este mestre deve ser excluido, caso contrario a contagem nao sera "
	#define STR0103 "finalizada."
	#define STR0104 "Atencao"
	#define STR0105 "Deseja excluir este mestre de inventario?"
	#define STR0106 "porem foi detectada a ocorrencia de inventario para este mestre!"
	#define STR0107 "sera necessario excluir esta contagem, caso contrario a contagem nao sera "
	#define STR0108 "Deseja excluir a contagem atual?"
	#define STR0109 "Leia o codigo do"
	#define STR0110 "Inválido"
#else
	#ifdef ENGLISH
		#define STR0001 "Operator not registered"
		#define STR0002 "Warning"
		#define STR0003 "Inventory"
		#define STR0004 "Resp. Code"
		#define STR0005 "Warehouse "
		#define STR0006 "Address"
		#define STR0007 "Quantity"
		#define STR0008 "Label"
		#define STR0009 "Product"
		#define STR0010 "Do you want to end the counting?"
		#define STR0011 "Error when saving the inventory"
		#define STR0012 "ERROR"
		#define STR0013 "Inventory concluded"
		#define STR0014 "The number of necessary countings was not reached"
		#define STR0015 "Inv. in progress"
		#define STR0016 "Resp. for inventory code not registered"
		#define STR0017 "Attention"
		#define STR0018 "Inventory concluded"
		#define STR0019 "Operator executing inventory at another terminal"
		#define STR0020 "Invalid label"
		#define STR0021 "Warning"
		#define STR0022 "Incorrect warehouse and address."
		#define STR0023 "The correct way is:"
		#define STR0024 "Address not registered."
		#define STR0025 "Product belongs to the address:"
		#define STR0026 "Code already read"
		#define STR0027 "Invalid reading"
		#define STR0028 "Invalid label."
		#define STR0029 "Invalid label!!"
		#define STR0030 "Product not registered."
		#define STR0031 "Product different to what should be stocked."
		#define STR0032 "Please, wait..."
		#define STR0033 "No product was stoicked. Confirm Zero stock?"
		#define STR0034 "Configure parameters MV_VLDTINV and MV_INVAUT"
		#define STR0035 "Go to the Warehouse"
		#define STR0036 " Address "
		#define STR0037 "Product not addressed"
		#define STR0038 "Inventario"
		#define STR0039 "Selecione:"
		#define STR0040 "Mestre"
		#define STR0041 "Endereco"
		#define STR0042 "Necessario ativar o parametro MV_CBPE012"
		#define STR0043 "Informacao"
		#define STR0044 "Leia a Etiqueta de"
		#define STR0045 "Produto p/ localizar"
		#define STR0046 "mestre de inventario"
		#define STR0047 "Armazem"
		#define STR0048 "Endereco p/ localizar"
		#define STR0049 "Nao existem Produtos para este endereco. A contagem nao sera finalizada!"
		#define STR0050 "-->Mestre:"
		#define STR0051 " - Erro na rotina automatica"
		#define STR0052 "Mestre "
		#define STR0053 " foi finalizado com sucesso"
		#define STR0054 "--> Mestre: "
		#define STR0055 " - Nao foi finalizado"
		#define STR0056 "- Contagem divergente"
		#define STR0057 "- Inventario bloqueado para auditoria"
		#define STR0058 "Inventario bloqueado para Auditoria"
		#define STR0059 "Operador ja realizou contagem para o inventario"
		#define STR0060 "Sem permissao"
		#define STR0061 "Somente o Operador "
		#define STR0062 " pode dar continuidade a este inventario"
		#define STR0063 "Contagens == 1"
		#define STR0064 ", produto pertence a um pallet "
		#define STR0065 "Produto nao localizado na tabela de saldos fisicos(SB2)."
		#define STR0066 'Produto nao pertence a(s) classe(s) "'
		#define STR0067 '" da curva ABC!'
		#define STR0068 "Etiqueta de produto sem endereco"
		#define STR0069 "Produto sem controle de endereco"
		#define STR0070 "Produto com "
		#define STR0071 "Qtde variavel"
		#define STR0072 "Quantidade Invalida"
		#define STR0073 "Nao eh necessario a recontagem!!!"
		#define STR0074 "Produto ja auditado"
		#define STR0075 " Nao encontrado"
		#define STR0076 "atribuicao simbolica somente para nao validar a contagem"
		#define STR0077 "Incluindo Inventario"
		#define STR0078 "Erro na rotina automatica:"
		#define STR0079 "Produto: "
		#define STR0080 "Armazem: "
		#define STR0081 "Endereco:"
		#define STR0082 "Lote:    "
		#define STR0083 "Sub-Lote:"
		#define STR0084 "N.Serie: "
		#define STR0085 'Erro na rotina automatica, necessario excluir esta finalizacao pelo Mestre de Inventario'
		#define STR0086 "Acerto Estoque..."
		#define STR0087 "nao deve entrar"
		#define STR0088 "Etiqueta Invalida"
		#define STR0089 "Nao Iniciado"
		#define STR0090 "Em Andamento"
		#define STR0091 "Mestre de Inventario nao encontrado"
		#define STR0092 "Data"
		#define STR0093 "Status"
		#define STR0094 "Mestre de Inventario nao selecionado"
		#define STR0095 "Lote"
		#define STR0096 "SubLote"
		#define STR0097 "Serie"
		#define STR0098 "Produto nao localizado na tabela de demandas (SB3)!"
		#define STR0099 "Favor executar o recalculo do lote economico para atualizar a tabela de demandas!"
		#define STR0100 "Nao existem produtos para este endereco nos saldos do sistema, "
		#define STR0101 "nem foi detectada a ocorrencia de inventario para este mestre!"
		#define STR0102 "Este mestre deve ser excluido, caso contrario a contagem nao sera "
		#define STR0103 "finalizada."
		#define STR0104 "Atencao"
		#define STR0105 "Deseja excluir este mestre de inventario?"
		#define STR0106 "porem foi detectada a ocorrencia de inventario para este mestre!"
		#define STR0107 "sera necessario excluir esta contagem, caso contrario a contagem nao sera "
		#define STR0108 "Deseja excluir a contagem atual?"
		#define STR0109 "Leia o codigo do"
		#define STR0110 "Inválido"
	#else
		#define STR0001 "Operador nao cadastrado"
		#define STR0002 "Aviso"
		#define STR0003 "Inventario"
		#define STR0004 "Codigo Mestre"
		#define STR0005 "Armazem "
		#define STR0006 "Endereco"
		#define STR0007 "Quantidade"
		#define STR0008 "Etiqueta"
		#define STR0009 "Produto"
		#define STR0010 "Deseja finalizar a contagem?"
		#define STR0011 "Falha na gravacao do inventario"
		#define STR0012 "ERRO"
		#define STR0013 "Inventario concluido"
		#define STR0014 "Nao foi atingido o numero de contagens necessarias"
		#define STR0015 "Inv. em andamento"
		#define STR0016 "Codigo mestre de inventario nao cadastrado"
		#define STR0017 "Atencao"
		#define STR0018 "Inventario finalizado"
		#define STR0019 "Operador executando inventario em outro terminal"
		#define STR0020 "Etiqueta invalida"
		#define STR0021 "Aviso"
		#define STR0022 "Armazem e endereco incorreto."
		#define STR0023 "O correto seria:"
		#define STR0024 "Endereco nao cadastrado."
		#define STR0025 "Produto pertence ao endereco:"
		#define STR0026 "Codigo ja lido"
		#define STR0027 "Leitura invalida"
		#define STR0028 "Etiqueta invalida."
		#define STR0029 "Etiqueta invalida!!"
		#define STR0030 "Produto nao cadastrado."
		#define STR0031 "Produto diferente do que deve ser inventariado."
		#define STR0032 "Aguarde..."
		#define STR0033 "Nenhum produto foi inventariado, confirma estoque Zero"
		#define STR0034 "Configure os parametros MV_VLDTINV e MV_INVAUT"
		#define STR0035 "Va para o Armazem "
		#define STR0036 " Endereco "
		#define STR0037 "Produto nao enderecao"
		#define STR0038 "Inventario"
		#define STR0039 "Selecione:"
		#define STR0040 "Mestre"
		#define STR0041 "Endereco"
		#define STR0042 "Necessario ativar o parametro MV_CBPE012"
		#define STR0043 "Informacao"
		#define STR0044 "Leia a Etiqueta de"
		#define STR0045 "Produto p/ localizar"
		#define STR0046 "mestre de inventario"
		#define STR0047 "Armazem"
		#define STR0048 "Endereco p/ localizar"
		#define STR0049 "Nao existem Produtos para este endereco. A contagem nao sera finalizada!"
		#define STR0050 "-->Mestre:"
		#define STR0051 " - Erro na rotina automatica"
		#define STR0052 "Mestre "
		#define STR0053 " foi finalizado com sucesso"
		#define STR0054 "--> Mestre: "
		#define STR0055 " - Nao foi finalizado"
		#define STR0056 "- Contagem divergente"
		#define STR0057 "- Inventario bloqueado para auditoria"
		#define STR0058 "Inventario bloqueado para Auditoria"
		#define STR0059 "Operador ja realizou contagem para o inventario"
		#define STR0060 "Sem permissao"
		#define STR0061 "Somente o Operador "
		#define STR0062 " pode dar continuidade a este inventario"
		#define STR0063 "Contagens == 1"
		#define STR0064 ", produto pertence a um pallet "
		#define STR0065 "Produto nao localizado na tabela de saldos fisicos(SB2)."
		#define STR0066 'Produto nao pertence a(s) classe(s) "'
		#define STR0067 '" da curva ABC!'
		#define STR0068 "Etiqueta de produto sem endereco"
		#define STR0069 "Produto sem controle de endereco"
		#define STR0070 "Produto com "
		#define STR0071 "Qtde variavel"
		#define STR0072 "Quantidade Invalida"
		#define STR0073 "Nao eh necessario a recontagem!!!"
		#define STR0074 "Produto ja auditado"
		#define STR0075 " Nao encontrado"
		#define STR0076 "atribuicao simbolica somente para nao validar a contagem"
		#define STR0077 "Incluindo Inventario"
		#define STR0078 "Erro na rotina automatica:"
		#define STR0079 "Produto: "
		#define STR0080 "Armazem: "
		#define STR0081 "Endereco:"
		#define STR0082 "Lote:    "
		#define STR0083 "Sub-Lote:"
		#define STR0084 "N.Serie: "
		#define STR0085 'Erro na rotina automatica, necessario excluir esta finalizacao pelo Mestre de Inventario'
		#define STR0086 "Acerto Estoque..."
		#define STR0087 "nao deve entrar"
		#define STR0088 "Etiqueta Invalida"
		#define STR0089 "Nao Iniciado"
		#define STR0090 "Em Andamento"
		#define STR0091 "Mestre de Inventario nao encontrado"
		#define STR0092 "Data"
		#define STR0093 "Status"
		#define STR0094 "Mestre de Inventario nao selecionado"
		#define STR0095 "Lote"
		#define STR0096 "SubLote"
		#define STR0097 "Serie"
		#define STR0098 "Produto nao localizado na tabela de demandas (SB3)!"
		#define STR0099 "Favor executar o recalculo do lote economico para atualizar a tabela de demandas!"
		#define STR0100 "Nao existem produtos para este endereco nos saldos do sistema, "
		#define STR0101 "nem foi detectada a ocorrencia de inventario para este mestre!"
		#define STR0102 "Este mestre deve ser excluido, caso contrario a contagem nao sera "
		#define STR0103 "finalizada."
		#define STR0104 "Atencao"
		#define STR0105 "Deseja excluir este mestre de inventario?"
		#define STR0106 "porem foi detectada a ocorrencia de inventario para este mestre!"
		#define STR0107 "sera necessario excluir esta contagem, caso contrario a contagem nao sera "
		#define STR0108 "Deseja excluir a contagem atual?"
		#define STR0109 "Leia o codigo do"
		#define STR0110 "Inválido"
	#endif
#endif
