#IFDEF SPANISH
   #define STR0001 "Descripcion del Campo"
   #define STR0002 "Fc. Pago"
   #define STR0003 "Valor del Campo"
   #define STR0004 "Nro. Cont"
   #define STR0005 "Historial Complementar"
   #define STR0006 'Integracion'
   #define STR0007 'Contabilidad'
   #define STR0008 "Origen"
   #define STR0009 "Nro. P.O."
   #define STR0010 "Invoice"
   #define STR0011 "Vlr P.O."
   #define STR0012 "Buscar"
   #define STR0013 "Visualizar"
   #define STR0014 "Incluir"
   #define STR0015 "Modificar"
   #define STR0016 "Borrar"
   #define STR0017 "Re&vertir"
   #define STR0018 "Mantenimiento de Procesos."
   #define STR0019 "No hay area disponible para apertura del archivo temporal."
   #define STR0020 "Borrando Registros."
   #define STR0021 'Registro ya contabilizado, no puede ser borrado.'
   #define STR0022 "Grabando Archivo."
   #define STR0023 "No fueron incluidos Pedidos"
   #define STR0024 "Informacion"
   #define STR0025 "No hay registros a ser "
   #define STR0026 "visualizados"
   #define STR0027 "modificados"
   #define STR0028 "borrados"
   #define STR0029 "Aviso"
   #define STR0030 'Registro ya contabilizado, no puede ser '
   #define STR0031 'modificado'
   #define STR0032 'borrado'
   #define STR0033 'Registro del codigo 201 no puede ser modificado.'
   #define STR0034 'Por lo menos, debe haber un registro de PO para este proceso.'
   #define STR0035 'Modificacion de Detalles - '
   #define STR0036 'Gastos'
   #define STR0037 'P.O.'
   #define STR0038 '¨Confirma el Borrado? '
   #define STR0039 'Borrar'
   #define STR0040 "Calculadora"
   #define STR0041 "Help de Programa"
   #define STR0042 "Visualizar Item"
   #define STR0043 "Inclusion"
   #define STR0044 "Borrado"
   #define STR0045 "Modificacion"
   #define STR0046 "P.O."
   #define STR0047 "Ok - <Ctrl-O>"
   #define STR0048 "Anular - <Ctrl-X>"
   #define STR0049 'Tasa de D.I. no llenada.'
   #define STR0050 'Numero de DI debe ser llenado.'
   #define STR0051 'Factura complementar no puede ser llenada (Fact entregada en blanco).'
   #define STR0052 'DI ya archivada para otro proceso.'
   #define STR0053 'Fecha de DI no llenada.'
   #define STR0054 'Proceso ya archivado.'
   #define STR0055 "B.U. / Unid.Req. no archivado."
   #define STR0056 'Campo 201 no puede ser incluido.'
   #define STR0057 'Codigo 4xx no puede ser incluido sin numero de Fact. de entrada.'
   #define STR0058 'Campo no grabado en el archivo de link.'
   #define STR0059 'La fecha de pago no puede ser menor que la fecha de la D.I.'
   #define STR0060 'Invoice no archivada.'
   #define STR0061 'Esta Invoice es de una moneda diferente.'
   #define STR0062 'Esta Invoice es de un proveedor diferente.'
   #define STR0063 'Esta Invoice ya pertenece al proceso - '
   #define STR0064 'Esta Invoice ya fue incluida en este proceso.'
   #define STR0065 "El motivo debe ser llenado."
   #define STR0066 "Grabando Procesos..."
   #define STR0067 "Grabando Gastos..."
   #define STR0068 "Grabando P.O.'s..."
   #define STR0069 "Borrando Procesos."
   #define STR0070 "Borrando Gastos del Proceso."
   #define STR0071 "Borrando P.O.'s del Proceso."
   #define STR0072 "Nro.Po"
   #define STR0073 "Moneda"
   #define STR0074 "Valor"
   #define STR0075 "Reversion de procesos contabilizados"
   #define STR0076 "Proceso"
   #define STR0077 "B.U. / Unid. Req."
   #define STR0078 "Motivo"
   #define STR0079 '¨Confirma Reversion? '
   #define STR0080 'Reversion'
   #define STR0081 "Revertiendo"
   #define STR0082 "No hay movimientos a ser impresos."
   #define STR0083 "Impresion"
   #define STR0084 "Revertiendo..."
   #define STR0085 "Imprimiendo..."
   #define STR0086 "Fecha: "
   #define STR0087 "INFORME DE REVERSION DE PROCESOS CONTABILIZADOS"
   #define STR0088 "Pagina..: "
   #define STR0089 "Emision.: "
   #define STR0090 'HAWB'
   #define STR0091 'INVOICE'
   #define STR0092 'NRO.DI'
   #define STR0093 'ASIENTO'
   #define STR0094 'CTA.DEBITO'
   #define STR0095 'CTA.CRED.'
   #define STR0096 'VALOR'
   #define STR0097 'HISTORIAL'
   #define STR0098 'B.U./UNID.REQ.'
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Descricao do Campo"
      #define STR0002 "Dt. Pagto"
      #define STR0003 "Valor do Campo"
      #define STR0004 "Nr. Cont"
      #define STR0005 "Historico Complementar"
      #define STR0006 'Integracao'
      #define STR0007 'Contabilidade'
      #define STR0008 "Origem"
      #define STR0009 "Nro. P.O."
      #define STR0010 "Invoice"
      #define STR0011 "Vlr P.O."
      #define STR0012 "Pesquisar"
      #define STR0013 "Visual"
      #define STR0014 "Inclui"
      #define STR0015 "Altera"
      #define STR0016 "Exclui"
      #define STR0017 "E&stornar"
      #define STR0018 "Manuten‡„o de Processos."
      #define STR0019 "N„o ha area disponivel para abertura do arquivo temporario."
      #define STR0020 "Deletando Registros."
      #define STR0021 'Registro j  contabilizado, n„o pode ser excluido.'
      #define STR0022 "Gravando Arquivo."
      #define STR0023 "Não foram incluidos Pedidos"
      #define STR0024 "Informação"
      #define STR0025 "N„o exixtem registros a serem "
      #define STR0026 "visualizados"
      #define STR0027 "alterados"
      #define STR0028 "excluidos"
      #define STR0029 "Aviso"
      #define STR0030 'Registro j  contabilizado, n„o pode ser '
      #define STR0031 'alterado'
      #define STR0032 'excluido'
      #define STR0033 'Registro do c¢digo 201 n„o pode ser alterado.'
      #define STR0034 'Deve haver pelo menos um registro de PO para este processo.'
      #define STR0035 'Altera‡„o de Detalhes - '
      #define STR0036 'Despesas'
      #define STR0037 'P.O.'
      #define STR0038 'Confirma `a Exclusao ? '
      #define STR0039 'Excluir'
      #define STR0040 "Calculadora"
      #define STR0041 "Help de Programa"
      #define STR0042 "Visualizar Item"
      #define STR0043 "Inclusao"
      #define STR0044 "Exclusao"
      #define STR0045 "Alteracao"
      #define STR0046 "P.O."
      #define STR0047 "Ok - <Ctrl-O>"
      #define STR0048 "Cancelar - <Ctrl-X>"
      #define STR0049 'Taxa da D.I. n„o preenchida.'
      #define STR0050 'N£mero da DI deve ser preenchido.'
      #define STR0051 'Nota fiscal complementar n„o pode ser preenchida(NF entrega em branco).'
      #define STR0052 'DI j  cadastrada para outro processo.'
      #define STR0053 'Data da DI n„o preenchida.'
      #define STR0054 'Processo j  cadastrado.'
      #define STR0055 "B.U. / Unid.Req. n„o cadastrado."
      #define STR0056 'Campo 201 n„o pode ser incluido.'
      #define STR0057 'C¢digo 4xx n„o pode ser incluido sem n£mero de N.F. de entrada.'
      #define STR0058 'Campo n„o cadastrado no arquivo de link.'
      #define STR0059 'A data de pagto n„o pode ser menor que a data da D.I.'
      #define STR0060 'Invoice n„o cadastrada.'
      #define STR0061 'Esta Invoice ‚ de uma moeda diferente.'
      #define STR0062 'Esta Invoice ‚ de um fornecedor diferente.'
      #define STR0063 'Esta Invoice j  pertence ao processo - '
      #define STR0064 'Esta Invoice j  foi incluida neste processo.'
      #define STR0065 "O motivo deve ser preenchido."
      #define STR0066 "Gravando Processos..."
      #define STR0067 "Gravando Despesas..."
      #define STR0068 "Gravando P.O.'s..."
      #define STR0069 "Deletando Processos."
      #define STR0070 "Deletando Despesas do Processo."
      #define STR0071 "Deletando P.O.'s do Processo."
      #define STR0072 "Nr. Po"
      #define STR0073 "Moeda"
      #define STR0074 "Valor"
      #define STR0075 "Estorno de processos contabilizados"
      #define STR0076 "Processo"
      #define STR0077 "B.U. / Unid. Req."
      #define STR0078 "Motivo"
      #define STR0079 'Confirma o Estorno ? '
      #define STR0080 'Estorno'
      #define STR0081 "Estornando"
      #define STR0082 "N„o h  movimenta‡„os a serem impressas."
      #define STR0083 "Impressao"
      #define STR0084 "Estornando..."
      #define STR0085 "Imprimindo..."
      #define STR0086 "Data: "
      #define STR0087 "RELATORIO DE ESTORNO DE PROCESSOS CONTABILIZADOS"
      #define STR0088 "Pagina..: "
      #define STR0089 "Emissao.: "
      #define STR0090 'HAWB'
      #define STR0091 'INVOICE'
      #define STR0092 'NR. DI'
      #define STR0093 'LANCTO.'
      #define STR0094 'CTA.DEBITO'
      #define STR0095 'CTA.CRED.'
      #define STR0096 'VALOR'
      #define STR0097 'HISTORICO'
      #define STR0098 'B.U./UNID.REQ.'
   #ELSE
      #define STR0001 "Descricao do Campo"
      #define STR0002 "Dt. Pagto"
      #define STR0003 "Valor do Campo"
      #define STR0004 "Nr. Cont"
      #define STR0005 "Historico Complementar"
      #define STR0006 'Integracao'
      #define STR0007 'Contabilidade'
      #define STR0008 "Origem"
      #define STR0009 "Nro. P.O."
      #define STR0010 "Invoice"
      #define STR0011 "Vlr P.O."
      #define STR0012 "Pesquisar"
      #define STR0013 "Visual"
      #define STR0014 "Inclui"
      #define STR0015 "Altera"
      #define STR0016 "Exclui"
      #define STR0017 "E&stornar"
      #define STR0018 "Manuten‡„o de Processos."
      #define STR0019 "N„o ha area disponivel para abertura do arquivo temporario."
      #define STR0020 "Deletando Registros."
      #define STR0021 'Registro j  contabilizado, n„o pode ser excluido.'
      #define STR0022 "Gravando Arquivo."
      #define STR0023 "Não foram incluidos Pedidos"
      #define STR0024 "Informação"
      #define STR0025 "N„o exixtem registros a serem "
      #define STR0026 "visualizados"
      #define STR0027 "alterados"
      #define STR0028 "excluidos"
      #define STR0029 "Aviso"
      #define STR0030 'Registro j  contabilizado, n„o pode ser '
      #define STR0031 'alterado'
      #define STR0032 'excluido'
      #define STR0033 'Registro do c¢digo 201 n„o pode ser alterado.'
      #define STR0034 'Deve haver pelo menos um registro de PO para este processo.'
      #define STR0035 'Altera‡„o de Detalhes - '
      #define STR0036 'Despesas'
      #define STR0037 'P.O.'
      #define STR0038 'Confirma `a Exclusao ? '
      #define STR0039 'Excluir'
      #define STR0040 "Calculadora"
      #define STR0041 "Help de Programa"
      #define STR0042 "Visualizar Item"
      #define STR0043 "Inclusao"
      #define STR0044 "Exclusao"
      #define STR0045 "Alteracao"
      #define STR0046 "P.O."
      #define STR0047 "Ok - <Ctrl-O>"
      #define STR0048 "Cancelar - <Ctrl-X>"
      #define STR0049 'Taxa da D.I. n„o preenchida.'
      #define STR0050 'N£mero da DI deve ser preenchido.'
      #define STR0051 'Nota fiscal complementar n„o pode ser preenchida(NF entrega em branco).'
      #define STR0052 'DI j  cadastrada para outro processo.'
      #define STR0053 'Data da DI n„o preenchida.'
      #define STR0054 'Processo j  cadastrado.'
      #define STR0055 "B.U. / Unid.Req. n„o cadastrado."
      #define STR0056 'Campo 201 n„o pode ser incluido.'
      #define STR0057 'C¢digo 4xx n„o pode ser incluido sem n£mero de N.F. de entrada.'
      #define STR0058 'Campo n„o cadastrado no arquivo de link.'
      #define STR0059 'A data de pagto n„o pode ser menor que a data da D.I.'
      #define STR0060 'Invoice n„o cadastrada.'
      #define STR0061 'Esta Invoice ‚ de uma moeda diferente.'
      #define STR0062 'Esta Invoice ‚ de um fornecedor diferente.'
      #define STR0063 'Esta Invoice j  pertence ao processo - '
      #define STR0064 'Esta Invoice j  foi incluida neste processo.'
      #define STR0065 "O motivo deve ser preenchido."
      #define STR0066 "Gravando Processos..."
      #define STR0067 "Gravando Despesas..."
      #define STR0068 "Gravando P.O.'s..."
      #define STR0069 "Deletando Processos."
      #define STR0070 "Deletando Despesas do Processo."
      #define STR0071 "Deletando P.O.'s do Processo."
      #define STR0072 "Nr. Po"
      #define STR0073 "Moeda"
      #define STR0074 "Valor"
      #define STR0075 "Estorno de processos contabilizados"
      #define STR0076 "Processo"
      #define STR0077 "B.U. / Unid. Req."
      #define STR0078 "Motivo"
      #define STR0079 'Confirma o Estorno ? '
      #define STR0080 'Estorno'
      #define STR0081 "Estornando"
      #define STR0082 "N„o h  movimenta‡„os a serem impressas."
      #define STR0083 "Impressao"
      #define STR0084 "Estornando..."
      #define STR0085 "Imprimindo..."
      #define STR0086 "Data: "
      #define STR0087 "RELATORIO DE ESTORNO DE PROCESSOS CONTABILIZADOS"
      #define STR0088 "Pagina..: "
      #define STR0089 "Emissao.: "
      #define STR0090 'HAWB'
      #define STR0091 'INVOICE'
      #define STR0092 'NR. DI'
      #define STR0093 'LANCTO.'
      #define STR0094 'CTA.DEBITO'
      #define STR0095 'CTA.CRED.'
      #define STR0096 'VALOR'
      #define STR0097 'HISTORICO'
      #define STR0098 'B.U./UNID.REQ.'
   #ENDIF
#ENDIF
