#IFDEF SPANISH
   #define STR0001 "Consulta de Invoices por Proveedor"
   #define STR0002 'Stock'
   #define STR0003 'Divisas '
   #define STR0004 'Transito'
   #define STR0005 "­No hay registros a ser procesados!"
   #define STR0006 "Informacion"
   #define STR0007 "1- No Contabilizados"
   #define STR0008 "2- Contabilizados"
   #define STR0009 "3- Ambos"
   #define STR0010 "Proveedor"
   #define STR0011 "Informe"
   #define STR0012 "­No hay registros a ser consultados!"
   #define STR0013 "Imprimiendo Invoice: "
   #define STR0014 'Codigo..: '
   #define STR0015 'Todos'
   #define STR0016 "Informe de Invoices"
   #define STR0017 "No Contabilizados"
   #define STR0018 "Contabilizados"
   #define STR0019 "Ambos"
   #define STR0020 "Pagina..: "
   #define STR0021 "Emision.: "
   #define STR0022 "Invoice"
   #define STR0023 "B.U./C.Costo"
   #define STR0024 "Fc.Emision"
   #define STR0025 "Moneda"
   #define STR0026 "Valor FOB"
   #define STR0027 "Status"
   #define STR0028 "Nro.Contab."
   #define STR0029 "Fc.Contab."
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Consulta de Invoices por Fornecedor"
      #define STR0002 'Estoque'
      #define STR0003 'Divisas '
      #define STR0004 'Transito'
      #define STR0005 "Não há registros a serem processados !"
      #define STR0006 "Informação"
      #define STR0007 "1- Não Contabilizados"
      #define STR0008 "2- Contabilizados"
      #define STR0009 "3- Ambos"
      #define STR0010 "Fornecedor"
      #define STR0011 "Relatório"
      #define STR0012 "Não há registros a serem consultados !"
      #define STR0013 "Imprimindo Invoice: "
      #define STR0014 'Codigo..: '
      #define STR0015 'Todos'
      #define STR0016 "Relatório de Invoices"
      #define STR0017 "Não Contabilizados"
      #define STR0018 "Contabilizados"
      #define STR0019 "Ambos"
      #define STR0020 "Pagina..: "
      #define STR0021 "Emissão.: "
      #define STR0022 "Invoice"
      #define STR0023 "B.U./C.Custo"
      #define STR0024 "Dt.Emissão"
      #define STR0025 "Moeda"
      #define STR0026 "Valor FOB"
      #define STR0027 "Status"
      #define STR0028 "Nr.Contab."
      #define STR0029 "Dt.Contab."
   #ELSE
      #define STR0001 "Consulta de Invoices por Fornecedor"
      #define STR0002 'Estoque'
      #define STR0003 'Divisas '
      #define STR0004 'Transito'
      #define STR0005 "Não há registros a serem processados !"
      #define STR0006 "Informação"
      #define STR0007 "1- Não Contabilizados"
      #define STR0008 "2- Contabilizados"
      #define STR0009 "3- Ambos"
      #define STR0010 "Fornecedor"
      #define STR0011 "Relatório"
      #define STR0012 "Não há registros a serem consultados !"
      #define STR0013 "Imprimindo Invoice: "
      #define STR0014 'Codigo..: '
      #define STR0015 'Todos'
      #define STR0016 "Relatório de Invoices"
      #define STR0017 "Não Contabilizados"
      #define STR0018 "Contabilizados"
      #define STR0019 "Ambos"
      #define STR0020 "Pagina..: "
      #define STR0021 "Emissão.: "
      #define STR0022 "Invoice"
      #define STR0023 "B.U./C.Custo"
      #define STR0024 "Dt.Emissão"
      #define STR0025 "Moeda"
      #define STR0026 "Valor FOB"
      #define STR0027 "Status"
      #define STR0028 "Nr.Contab."
      #define STR0029 "Dt.Contab."
   #ENDIF
#ENDIF
