#IFDEF SPANISH
   #define STR0001 "NO HAY AREA DISPONIBLE PARA APERTURA DEL ARCHIVO TEMPORAL"
   #define STR0002 "Informacion"
   #define STR0003 "No hay items para generacion de TXT's"
   #define STR0004 '¨CONFIRMA GENERACION DE ARCHIVOS? '
   #define STR0005 'GENERACION DE ARCHIVOS'
   #define STR0006 "Archivo(s) Generado(s) :"
   #define STR0007 "Fecha inicial mayor que fecha final"
   #define STR0008 "Generando archivo temporal - Libros Fiscales"
   #define STR0009 "Generando archivo temporal - Bymap"
   #define STR0010 "Generando archivos de Libros Fiscales"
   #define STR0011 "Archivo Libros Fiscales.............: "
   #define STR0012 "Generando Libros Fiscales / Items"
   #define STR0013 "Archivo Libros Fiscales / Items.: "
   #define STR0014 "Actualizando Livros Fiscales / Items"
   #define STR0015 "Generando archivo de Costos"
   #define STR0016 "Archivo Costos ( Bymap ).......: "
   #define STR0017 "Actualizando archivo de Costos"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "NÇO HA µREA DISPONÖVEL PARA ABERTURA DO ARQUIVO TEMPORµRIO"
      #define STR0002 "Informa‡Æo"
      #define STR0003 "NÆo h  ¡tens para gera‡Æo de TXT's"
      #define STR0004 'CONFIRMA A GERA€ÇO DE ARQUIVOS ? '
      #define STR0005 'GERA€ÇO DE ARQUIVOS'
      #define STR0006 "Arquivo(s) Gerado(s) :"
      #define STR0007 "Data inicial maior que a data final"
      #define STR0008 "Gerando arquivo tempor rio - Livros Fiscais"
      #define STR0009 "Gerando arquivo tempor rio - Bymap"
      #define STR0010 "Gerando arquivos de Livros Fiscais"
      #define STR0011 "Arquivo Livros Fiscais.............: "
      #define STR0012 "Gerando Livros Fiscais / Itens"
      #define STR0013 "Arquivo Livros Fiscais / Itens.: "
      #define STR0014 "Atualizando Livros Fiscais / Itens"
      #define STR0015 "Gerando arquivo de Custos"
      #define STR0016 "Arquivo Custos ( Bymap ).......: "
      #define STR0017 "Atualizando arquivo de Custos"
   #ELSE
      #define STR0001 "NÇO HA µREA DISPONÖVEL PARA ABERTURA DO ARQUIVO TEMPORµRIO"
      #define STR0002 "Informa‡Æo"
      #define STR0003 "NÆo h  ¡tens para gera‡Æo de TXT's"
      #define STR0004 'CONFIRMA A GERA€ÇO DE ARQUIVOS ? '
      #define STR0005 'GERA€ÇO DE ARQUIVOS'
      #define STR0006 "Arquivo(s) Gerado(s) :"
      #define STR0007 "Data inicial maior que a data final"
      #define STR0008 "Gerando arquivo tempor rio - Livros Fiscais"
      #define STR0009 "Gerando arquivo tempor rio - Bymap"
      #define STR0010 "Gerando arquivos de Livros Fiscais"
      #define STR0011 "Arquivo Livros Fiscais.............: "
      #define STR0012 "Gerando Livros Fiscais / Itens"
      #define STR0013 "Arquivo Livros Fiscais / Itens.: "
      #define STR0014 "Atualizando Livros Fiscais / Itens"
      #define STR0015 "Gerando arquivo de Custos"
      #define STR0016 "Arquivo Custos ( Bymap ).......: "
      #define STR0017 "Atualizando arquivo de Custos"
   #ENDIF
#ENDIF
