#IFDEF SPANISH
   #define STR0001 "Buscar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Modificar"
   #define STR0005 "Borrar"
   #define STR0006 "Archivo C.F.O."
   #define STR0007 "Mantenimiento de C.F.O."
   #define STR0008 '®Confirma el borrado?'
   #define STR0009 'Borrar'
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Pesquisar"
      #define STR0002 "Visual"
      #define STR0003 "Inclui"
      #define STR0004 "Altera"
      #define STR0005 "Exclui"
      #define STR0006 "Cadastro C.F.O."
      #define STR0007 "Manutená∆o de C.F.O."
      #define STR0008 'Confirma a exclus∆o ? '
      #define STR0009 'Excluir'
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visual"
      #define STR0003 "Inclui"
      #define STR0004 "Altera"
      #define STR0005 "Exclui"
      #define STR0006 "Cadastro C.F.O."
      #define STR0007 "Manutená∆o de C.F.O."
      #define STR0008 'Confirma a exclus∆o ? '
      #define STR0009 'Excluir'
   #ENDIF
#ENDIF
