#IFDEF SPANISH
   #define STR0001 "Este informe imprimira el Shipping Confirmation"
   #define STR0002 "Shipping Confirmation"
   #define STR0003 "Shipment Confirmation"
   #define STR0004 "No hay area disponible para apertura del Archivo de Work"
   #define STR0005 "Informacion"
   #define STR0006 "Procesando Archivo Temporal..."
   #define STR0007 "Fecha de Hoy"
   #define STR0008 "Proveedor"
   #define STR0009 "Importador"
   #define STR0010 "Todos"
   #define STR0011 "Nro.P.O."
   #define STR0012 "P/N"
   #define STR0013 "I/L Number"
   #define STR0014 "Item"
   #define STR0015 "Nro.S.I."
   #define STR0016 "Cantidad"
   #define STR0017 "Fc. Emb. en P.O."
   #define STR0018 "Embarque"
   #define STR0019 "Estatus"
   #define STR0020 "Buscando Embarques..."
   #define STR0021 "Cartas"
   #define STR0022 "Fecha de Hoy debe ser informada"
   #define STR0023 "Proveedor no archivado"
   #define STR0024 "Importador debe ser informado"
   #define STR0025 "Importador no archivado"
   #define STR0026 "Procesando Item: "
   #define STR0027 "ESPERANDO EMBARQUE PARA "
   #define STR0028 "NO EMBARCADO EN "
   #define STR0029 " /ESPERANDO"
   #define STR0030 "Atraso"
   #define STR0031 "Preven"
   #define STR0032 "EMBARQUE CONFIRMADO P/ "
   #define STR0033 "EMBARQUE CONFIRMADO PARA "
   #define STR0034 "P.O. "
   #define STR0035 " NO GRABADO EN ARCHIVO SW2 - W5/W2"
   #define STR0036 "COD. DEL ITEM/FABR./PROV. "
   #define STR0037 " NO ARCHIVADO EN LI000 - IG/LI"
   #define STR0038 "Ningun registro fue selecionado"
   #define STR0039 "No hay Embarques para esa carta."
   #define STR0040 "Emision de Carta con Confirmacion de Embarque"
   #define STR0041 "Procesando Informe..."
   #define STR0042 "Imprimiendo Proveedor: "
   #define STR0043 'SUBJECT: SHIPPING CONFIRMATION '
   #define STR0044 "PLEASE SEND TO US A FORWARDER SHIPPERS LETTER'S COPY, COMMERCIAL INVOICE, HAWB NUMBER FOR"
   #define STR0045 "ITEMS IN ATTACH, IF THE SHIPMENT HAD BEEN ALREADY EFFECTED."
   #define STR0046 "FOR ITEMS THAT THE SHIPMENT WERE NOT SHIPPED IN THE ABOVE DATE, PLEASE INFORM TO US WHEN"
   #define STR0047 "YOU'LL BE ABLE TO SHIP IT. THANK YOU VERY MUCH AND BEST REGARDS,"
   #define STR0048 'SHIPMENT CONFIRMATION'
   #define STR0049 "TO.........: "
   #define STR0050 "ATTN.......: "
   #define STR0051 "FAX NR.....: "
   #define STR0052 "PHONE NR...: "
   #define STR0053 "PLEASE SEND  US  SHIPPING  DETAILS, COPY  OF  COMMERCIAL  INVOICE, HAWB OR B/L  NUMBER  FOR  THE"
   #define STR0054 "ATTACHED ITEMS, IF SHIPMENT IS ALREADY EFFECTED."
   #define STR0055 "IN  THE  CONTRARY,  PLEASE  INFORM US THE  SHIPPING SCHEDULE, AS SOON AS  JUST  POSSIBLE.  WE'RE"
   #define STR0056 "WAITING FOR YOUR URGENT REPLY."
   #define STR0057 "THANKS AND REGARDS"
   #define STR0058 "Imprimindo Item: "
   #define STR0059 'REMARKS: PLEASE INFORM THE CONFIRMED SHIP DATE IN THIS PAPER'
   #define STR0060 'NUMBER PO'
   #define STR0061 'PART NUMBER'
   #define STR0062 'I/L NUMBER'
   #define STR0063 'S.I.'
   #define STR0064 'QUANTITY'
   #define STR0065 'REQ.SHIP'
   #define STR0066 'CONFIRMED SHIP.'
   #define STR0067 'DATE P.O.'
   #define STR0068 'CODE'
   #define STR0069 'DATE'
   #define STR0070 'DATE DD/MM/YY'
   #define STR0071 ' INFORME DEL SHIPPING INFORMATION  '
   #define STR0072 'Num. P.O.'
   #define STR0073 'Cantidad'
   #define STR0074 'Valor Unit.'
   #define STR0075 'Fc. Emb.'
   #define STR0076 'ESTATUS'
   #define STR0077 'Codigo'
   #define STR0078 "Date: "
   #define STR0079 "Page: "
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Este relatÛrio imprimir· o Shipping Confirmation"
      #define STR0002 "Shipping Confirmation"
      #define STR0003 "Shipment Confirmation"
      #define STR0004 "N∆o h† †rea dispon°vel para abertura do Cadastro de Work"
      #define STR0005 "Informaá∆o"
      #define STR0006 "Processando Arquivo Tempor·rio..."
      #define STR0007 "Data Base"
      #define STR0008 "Fornecedor"
      #define STR0009 "Importador"
      #define STR0010 "Todos"
      #define STR0011 "Nß P.O."
      #define STR0012 "P/N"
      #define STR0013 "I/L Number"
      #define STR0014 "Item"
      #define STR0015 "Nß S.I."
      #define STR0016 "Quantidade"
      #define STR0017 "Dt. Emb. no P.O."
      #define STR0018 "Embarque"
      #define STR0019 "Status"
      #define STR0020 "Pesquisando Embarques..."
      #define STR0021 "Cartas"
      #define STR0022 "Data Base deve ser informada"
      #define STR0023 "Fornecedor n∆o cadastrado"
      #define STR0024 "Importador deve ser informado"
      #define STR0025 "Importador n∆o cadastrado"
      #define STR0026 "Processando Item: "
      #define STR0027 "AGUARDANDO EMBARQUE PARA "
      #define STR0028 "NAO EMBARCADO EM "
      #define STR0029 " /AGUARDANDO"
      #define STR0030 "Atraso"
      #define STR0031 "Preven"
      #define STR0032 "EMBARQUE CONFIRMADO P/ "
      #define STR0033 "EMBARQUE CONFIRMADO PARA "
      #define STR0034 "P.O. "
      #define STR0035 " N«O CADASTRADO NO ARQUIVO SW2 - W5/W2"
      #define STR0036 "COD. DO ITEM/FABR./FORN. "
      #define STR0037 " N«O CADASTRADO NO LI000 - IG/LI"
      #define STR0038 "Nenhum registro foi selecionado"
      #define STR0039 "N∆o existe Embarques para essa carta."
      #define STR0040 "Emissao de Carta com Confirmacao de Embarque"
      #define STR0041 "Processando Relatorio..."
      #define STR0042 "Imprimindo Fornecedor: "
      #define STR0043 'SUBJECT: SHIPPING CONFIRMATION '
      #define STR0044 "PLEASE SEND TO US A FORWARDER SHIPPERS LETTER'S COPY, COMMERCIAL INVOICE, HAWB NUMBER FOR"
      #define STR0045 "ITEMS IN ATTACH, IF THE SHIPMENT HAD BEEN ALREADY EFFECTED."
      #define STR0046 "FOR ITEMS THAT THE SHIPMENT WERE NOT SHIPPED IN THE ABOVE DATE, PLEASE INFORM TO US WHEN"
      #define STR0047 "YOU'LL BE ABLE TO SHIP IT. THANK YOU VERY MUCH AND BEST REGARDS,"
      #define STR0048 'SHIPMENT CONFIRMATION'
      #define STR0049 "TO.........: "
      #define STR0050 "ATTN.......: "
      #define STR0051 "FAX NR.....: "
      #define STR0052 "PHONE NR...: "
      #define STR0053 "PLEASE SEND  US  SHIPPING  DETAILS, COPY  OF  COMMERCIAL  INVOICE, HAWB OR B/L  NUMBER  FOR  THE"
      #define STR0054 "ATTACHED ITEMS, IF SHIPMENT IS ALREADY EFFECTED."
      #define STR0055 "IN  THE  CONTRARY,  PLEASE  INFORM US THE  SHIPPING SCHEDULE, AS SOON AS  JUST  POSSIBLE.  WE'RE"
      #define STR0056 "WAITING FOR YOUR URGENT REPLY."
      #define STR0057 "THANKS AND REGARDS"
      #define STR0058 "Imprimindo Item: "
      #define STR0059 'REMARKS: PLEASE INFORM THE CONFIRMED SHIP DATE IN THIS PAPER'
      #define STR0060 'NUMBER PO'
      #define STR0061 'PART NUMBER'
      #define STR0062 'I/L NUMBER'
      #define STR0063 'S.I.'
      #define STR0064 'QUANTITY'
      #define STR0065 'REQ.SHIP'
      #define STR0066 'CONFIRMED SHIP.'
      #define STR0067 'DATE P.O.'
      #define STR0068 'CODE'
      #define STR0069 'DATE'
      #define STR0070 'DATE DD/MM/YY'
      #define STR0071 ' RELATORIO DO SHIPPING INFORMATION  '
      #define STR0072 'Num. P.O.'
      #define STR0073 'Quantidade'
      #define STR0074 'Valor Unit.'
      #define STR0075 'Dt. Emb.'
      #define STR0076 'STATUS'
      #define STR0077 'Codigo'
      #define STR0078 "Date: "
      #define STR0079 "Page: "
   #ELSE
      #define STR0001 "Este relatÛrio imprimir· o Shipping Confirmation"
      #define STR0002 "Shipping Confirmation"
      #define STR0003 "Shipment Confirmation"
      #define STR0004 "N∆o h† †rea dispon°vel para abertura do Cadastro de Work"
      #define STR0005 "Informaá∆o"
      #define STR0006 "Processando Arquivo Tempor·rio..."
      #define STR0007 "Data Base"
      #define STR0008 "Fornecedor"
      #define STR0009 "Importador"
      #define STR0010 "Todos"
      #define STR0011 "Nß P.O."
      #define STR0012 "P/N"
      #define STR0013 "I/L Number"
      #define STR0014 "Item"
      #define STR0015 "Nß S.I."
      #define STR0016 "Quantidade"
      #define STR0017 "Dt. Emb. no P.O."
      #define STR0018 "Embarque"
      #define STR0019 "Status"
      #define STR0020 "Pesquisando Embarques..."
      #define STR0021 "Cartas"
      #define STR0022 "Data Base deve ser informada"
      #define STR0023 "Fornecedor n∆o cadastrado"
      #define STR0024 "Importador deve ser informado"
      #define STR0025 "Importador n∆o cadastrado"
      #define STR0026 "Processando Item: "
      #define STR0027 "AGUARDANDO EMBARQUE PARA "
      #define STR0028 "NAO EMBARCADO EM "
      #define STR0029 " /AGUARDANDO"
      #define STR0030 "Atraso"
      #define STR0031 "Preven"
      #define STR0032 "EMBARQUE CONFIRMADO P/ "
      #define STR0033 "EMBARQUE CONFIRMADO PARA "
      #define STR0034 "P.O. "
      #define STR0035 " N«O CADASTRADO NO ARQUIVO SW2 - W5/W2"
      #define STR0036 "COD. DO ITEM/FABR./FORN. "
      #define STR0037 " N«O CADASTRADO NO LI000 - IG/LI"
      #define STR0038 "Nenhum registro foi selecionado"
      #define STR0039 "N∆o existe Embarques para essa carta."
      #define STR0040 "Emissao de Carta com Confirmacao de Embarque"
      #define STR0041 "Processando Relatorio..."
      #define STR0042 "Imprimindo Fornecedor: "
      #define STR0043 'SUBJECT: SHIPPING CONFIRMATION '
      #define STR0044 "PLEASE SEND TO US A FORWARDER SHIPPERS LETTER'S COPY, COMMERCIAL INVOICE, HAWB NUMBER FOR"
      #define STR0045 "ITEMS IN ATTACH, IF THE SHIPMENT HAD BEEN ALREADY EFFECTED."
      #define STR0046 "FOR ITEMS THAT THE SHIPMENT WERE NOT SHIPPED IN THE ABOVE DATE, PLEASE INFORM TO US WHEN"
      #define STR0047 "YOU'LL BE ABLE TO SHIP IT. THANK YOU VERY MUCH AND BEST REGARDS,"
      #define STR0048 'SHIPMENT CONFIRMATION'
      #define STR0049 "TO.........: "
      #define STR0050 "ATTN.......: "
      #define STR0051 "FAX NR.....: "
      #define STR0052 "PHONE NR...: "
      #define STR0053 "PLEASE SEND  US  SHIPPING  DETAILS, COPY  OF  COMMERCIAL  INVOICE, HAWB OR B/L  NUMBER  FOR  THE"
      #define STR0054 "ATTACHED ITEMS, IF SHIPMENT IS ALREADY EFFECTED."
      #define STR0055 "IN  THE  CONTRARY,  PLEASE  INFORM US THE  SHIPPING SCHEDULE, AS SOON AS  JUST  POSSIBLE.  WE'RE"
      #define STR0056 "WAITING FOR YOUR URGENT REPLY."
      #define STR0057 "THANKS AND REGARDS"
      #define STR0058 "Imprimindo Item: "
      #define STR0059 'REMARKS: PLEASE INFORM THE CONFIRMED SHIP DATE IN THIS PAPER'
      #define STR0060 'NUMBER PO'
      #define STR0061 'PART NUMBER'
      #define STR0062 'I/L NUMBER'
      #define STR0063 'S.I.'
      #define STR0064 'QUANTITY'
      #define STR0065 'REQ.SHIP'
      #define STR0066 'CONFIRMED SHIP.'
      #define STR0067 'DATE P.O.'
      #define STR0068 'CODE'
      #define STR0069 'DATE'
      #define STR0070 'DATE DD/MM/YY'
      #define STR0071 ' RELATORIO DO SHIPPING INFORMATION  '
      #define STR0072 'Num. P.O.'
      #define STR0073 'Quantidade'
      #define STR0074 'Valor Unit.'
      #define STR0075 'Dt. Emb.'
      #define STR0076 'STATUS'
      #define STR0077 'Codigo'
      #define STR0078 "Date: "
      #define STR0079 "Page: "
   #ENDIF
#ENDIF
