#IFDEF SPANISH
   #define STR0001 "­Funcion no autorizada para este modulo!"
   #define STR0002 "Aviso"
   #define STR0003 "Buscar"
   #define STR0004 "Visualizar"
   #define STR0005 "Incluir"
   #define STR0006 "Modificar"
   #define STR0007 "Revertir"
   #define STR0008 "Purchase Order"
   #define STR0009 "Reversion"
   #define STR0010 '   Anuencia    '
   #define STR0011 "Nro.SI"
   #define STR0012 "Posicion"
   #define STR0013 "Item"
   #define STR0014 "Part Number"
   #define STR0015 'No'
   #define STR0016 'Si'
   #define STR0017 "Anuencia"
   #define STR0018 "Descripcion en Ingles"
   #define STR0019 "Fabricante"
   #define STR0020 "Uni"
   #define STR0021 "Vlr. Total Media"
   #define STR0022 "Cantidad"
   #define STR0023 "Ctd Embarcada"
   #define STR0024 "Saldo Ctd"
   #define STR0025 "Precio Unit"
   #define STR0026 "Valor Total"
   #define STR0027 "Embarque"
   #define STR0028 "Entrega"
   #define STR0029 "Si"
   #define STR0030 "No"
   #define STR0031 "Forecast"
   #define STR0032 "Registro en Ministerio / Organo Publico"
   #define STR0033 "Salvar & Salir"
   #define STR0034 '¨Confirma Grabacion? '
   #define STR0035 'Portada del P.O.'
   #define STR0036 "Pedido no puede ser revertido, pues posee proceso en marcha."
   #define STR0037 "Atencion"
   #define STR0038 "Nro.SI"
   #define STR0039 "Precio"
   #define STR0040 "P.O. "
   #define STR0041 " de "
   #define STR0042 "Nro. P.O.:"
   #define STR0043 "Fecha: "
   #define STR0044 "Prov:"
   #define STR0045 "Total Fob: "
   #define STR0046 "Todos"
   #define STR0047 "Busqueda de Items"
   #define STR0048 "Procesando Item "
   #define STR0049 "REGENERANDO ARCHIVO DE TRABAJO"
   #define STR0050 "Leyendo Items del P.O. "
   #define STR0051 "Seleccion de S.I."
   #define STR0052 "C.C."
   #define STR0053 'S.I. Nro'
   #define STR0054 '(F3-Help)'
   #define STR0055 '(F4-Help)'
   #define STR0056 "¨Desea Salir?"
   #define STR0057 "Confirmacion de Salida"
   #define STR0058 "Descripcion en Ingles"
   #define STR0059 "Nombre"
   #define STR0060 "Unidad"
   #define STR0061 "Seleccion de Items"
   #define STR0062 "Busqueda/P.N."
   #define STR0063 "Cambia S.I."
   #define STR0064 "Cotejo"
   #define STR0065 'S.I. Nro '
   #define STR0066 "­Proveedor debe ser el mismo ya informado! ("
   #define STR0067 "Informacion"
   #define STR0068 " (CON PREANUENCIA)"
   #define STR0069 " (SIN PREANUENCIA)"
   #define STR0070 "Datos del Item"
   #define STR0071 'Codigo Item'
   #define STR0072 'Fabricante'
   #define STR0073 '¨Anuencia?'
   #define STR0074 'Saldo Ctd'
   #define STR0075 'Reg. Ministerio'
   #define STR0076 'Embarcado'
   #define STR0077 'Precio Unitario'
   #define STR0078 'Costo Total'
   #define STR0079 'Embarque'
   #define STR0080 'Entrega'
   #define STR0081 'Otros Codigos de Fabricante (Direcciones p/ L.I.)'
   #define STR0082 "(F4-Help)"
   #define STR0083 "N§ S.I."
   #define STR0084 "Precio Unitario"
   #define STR0085 "Precio Total"
   #define STR0086 "Cotejo Final"
   #define STR0087 "Nro. P.O.: "
   #define STR0088 "Fecha.: "
   #define STR0089 "Modificacion "
   #define STR0090 "Fob Total "
   #define STR0091 "Graba P.O."
   #define STR0092 "Mod.Fechas"
   #define STR0093 ' de solicitud no informado'
   #define STR0094 " no archivado"
   #define STR0095 'Numero de solicitud no informado'
   #define STR0096 'Solicitud no archivada'
   #define STR0097 "Moneda de Solicitud es diferente de la moneda del Pedido."
   #define STR0098 "Buscando Items de S.I."
   #define STR0099 'No hay items de esta solicitud a ser seleccionados'
   #define STR0100 ", pues P.O. fue Incluido por Integracion"
   #define STR0101 "Procesando Item: "
   #define STR0102 "Items con valor unitario en cero"
   #define STR0103 "Descuento no puede ser mayor que F.O.B + INLAND + PACKING "
   #define STR0104 "+ FRETE"
   #define STR0105 'Cierre'
   #define STR0106 "Generando Posiciones"
   #define STR0107 "Grabacion del P.O."
   #define STR0108 "El Numero del Pedido de MicroSiga es : "
   #define STR0109 "El Numero del Pedido es : "
   #define STR0110 "Grabando Posicion del Item: "
   #define STR0111 "Codigo N.C.M. no archivado"
   #define STR0112 "Codigos N.C.M.s no archivados"
   #define STR0113 "Codigos N.C.M.s y N.B.M. no archivados"
   #define STR0114 "Tipo de Flete Difiere de (PP-Prepaid / CC-Collect)"
   #define STR0115 "Tipo de Flete no puede ser Modificado, pues P.O. posee L.I"
   #define STR0116 "Este campo no puede ser llenado en la Inclusion"
   #define STR0117 'Item '
   #define STR0118 ' no archivado para el Fabr. '
   #define STR0119 ' / Prov. '
   #define STR0120 "Proveedor no llenado"
   #define STR0121 "Proveedor no archivado"
   #define STR0122 "Registro archivado como fabricante"
   #define STR0123 "Cliente no encontrado"
   #define STR0124 "Atencion - Numero de cotizacion no archivado"
   #define STR0125 'Condiccion de Pago no llenada '
   #define STR0126 'Condicion no puede ser Modificada, pues P.O. posee L.I.'
   #define STR0127 'Condicion no Archivada'
   #define STR0128 "Comprobando Items del P.O."
   #define STR0129 'Condicion no Archivada'
   #define STR0130 "Dias Pago no puede ser Modificado, pues P.O. posee L.I."
   #define STR0131 'Dias de pago no archivado'
   #define STR0132 "No existe este Medio de Transporte / Origen / Destino en el Archivo de Fletes"
   #define STR0133 "No existe este Medio de Transporte / Origen en el Archivo de Fletes"
   #define STR0134 "Incoterms no puede ser Modificado - P.O. posee L.I."
   #define STR0135 'Numero de resolucion diferente de 0,7/8,15'
   #define STR0136 "Moneda no puede ser modificada - P.O. posee LI"
   #define STR0137 'No hay cotizacion para esta moneda'
   #define STR0138 'Saldo de la cantidad no llenado'
   #define STR0139 'Saldo de la cantidad no puede ser negativo'
   #define STR0140 'Cantidad mayor que el saldo de la solicitud'
   #define STR0141 'Valor unitario no llenado'
   #define STR0142 'Valor unitario no puede ser negativo'
   #define STR0143 'Codigo '
   #define STR0144 ' no archivado'
   #define STR0145 'Fecha de embarque debe ser mayor que la fecha del P.O.'
   #define STR0146 'Fecha de entrega debe ser mayor o igual que la fecha de embarque'
   #define STR0147 ' no archivado p/ el fabr. '
   #define STR0148 ' y prov. '
   #define STR0149 'Fecha de entrega menor que el lead time operacional'
   #define STR0150 'Fecha de entrega menor que el lead time del item'
   #define STR0151 "Importador no puede ser modificado - P.O. posee L.I."
   #define STR0152 'Codigo del importador no llenado'
   #define STR0153 'Codigo del importador no archivado'
   #define STR0154 "Codigo informado no es de importador"
   #define STR0155 "Consignatario no puede ser modificado - P.O. posee L.I."
   #define STR0156 'Codigo de consignatario no archivado'
   #define STR0157 "Codigo informado no es de consignatario"
   #define STR0158 "Caracter diferente de 'S-Si' / 'N-No'"
   #define STR0159 "Esta informacion no puede ser modificada, el item ya posee L.I., reviertala."
   #define STR0160 "Item ya tiene ctd.embarcada, no puede ser modificado p/ con anuencia."
   #define STR0161 "Codigo de observacion inexistente"
   #define STR0162 "Exportador no archviado"
   #define STR0163 "Tipo de comision no puede ser llenado"
   #define STR0164 "Tipo de comision no llenado"
   #define STR0165 "Valor de comision no puede ser llenado"
   #define STR0166 "Valor de comision no llenado"
   #define STR0167 "Porcentaje de comision no puede ser llenado"
   #define STR0168 "Porcentaje de comision no llenado"
   #define STR0169 "Otr. Comis. no puede ser llenado"
   #define STR0170 "Otr. Comis. no llenado"
   #define STR0171 "Volumen cubico no puede ser negativo"
   #define STR0172 "Container de 20' no puede ser negativo"
   #define STR0173 "Container de 40' no puede ser negativo"
   #define STR0174 "Container de 40' HC no puede ser negativo"
   #define STR0175 "Otros no puede ser negativo"
   #define STR0176 "Procesando Item nro. "
   #define STR0177 'Fabricante no archivado para este item'
   #define STR0178 "Gastos"
   #define STR0179 "incluir get gastos en modificacion"
   #define STR0180 "Inland Charge"
   #define STR0181 "Packing Charge"
   #define STR0182 "Int'l Freight"
   #define STR0183 "Descuento"
   #define STR0184 "¨Confirma el "
   #define STR0185 " de este P.O.? "
   #define STR0186 "Confirmacion"
   #define STR0187 "Reversion en marcha..."
   #define STR0188 "Revertiendo UR: "
   #define STR0189 " SI: "
   #define STR0190 " Item: "
   #define STR0191 "Procesando Eventos"
   #define STR0192 'REVERSION DO P.O. - '
   #define STR0193 'TOTAL'
   #define STR0194 'SALDO'
   #define STR0195 "PO"
   #define STR0196 "Creando Archivo"
   #define STR0197 "Creando Indice 1"
   #define STR0198 "Procesando Archivo Temporal..."
   #define STR0199 "Creando Indice 2"
   #define STR0200 "Procesando Archivo Temporal..."
   #define STR0201 "Codigo"
   #define STR0202 "Generando Help de Fabricantes"
   #define STR0203 "Consulta Items/Fabricantes"
   #define STR0204 "Procesando Fabricante nr. "
   #define STR0205 "Nro.de S.I."
   #define STR0206 "Generando Help de S.I."
   #define STR0207 "Consulta "
   #define STR0208 " de la S.I."
   #define STR0209 "Procesando S.I. nro. "
   #define STR0210 "Fecha de entrega sugerida no llenada."
   #define STR0211 "Fecha de embarque sugerida no llenada."
   #define STR0212 'Modificacion de Fechas'
   #define STR0213 "Fecha Embarque"
   #define STR0214 "Prevision de Entrega"
   #define STR0215 "De:                          Para:"
   #define STR0216 "De:                            Para:"
   #define STR0217 "La prevision de entrega debe ser mayor que la de embarque."
   #define STR0218 "¨Confirma estas fechas para los items?"
   #define STR0219 "Grabando Registro Nro. "
   #define STR0220 "Generando Archivos de Trabajo..."
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Função não autorizada para este módulo !"
      #define STR0002 "Aviso"
      #define STR0003 "Pesquisar"
      #define STR0004 "Visual"
      #define STR0005 "Inclui"
      #define STR0006 "Altera"
      #define STR0007 "Estorna"
      #define STR0008 "Purchase Order"
      #define STR0009 "Estorno"
      #define STR0010 '   Anuencia    '
      #define STR0011 "No.SI"
      #define STR0012 "Posicao"
      #define STR0013 "Item"
      #define STR0014 "Part Number"
      #define STR0015 'Nao'
      #define STR0016 'Sim'
      #define STR0017 "Anuencia"
      #define STR0018 "Descricao em Ingles"
      #define STR0019 "Fabricante"
      #define STR0020 "Uni"
      #define STR0021 "Vlr. Total Midia"
      #define STR0022 "Quantidade"
      #define STR0023 "Qtde Embarcada"
      #define STR0024 "Saldo Qtde"
      #define STR0025 "Preco Unit"
      #define STR0026 "Valor Total"
      #define STR0027 "Embarque"
      #define STR0028 "Entrega"
      #define STR0029 "Sim"
      #define STR0030 "Nao"
      #define STR0031 "Forecast"
      #define STR0032 "Registro no Minist‚rio / OrgÆo P£blico"
      #define STR0033 "Salva & Sai"
      #define STR0034 'Confirma a Gravação ? '
      #define STR0035 'Capa do P.O.'
      #define STR0036 "Pedido não pode ser estornado, pois possui processo em andamento."
      #define STR0037 "Atenção"
      #define STR0038 "N§ SI"
      #define STR0039 "Preco"
      #define STR0040 "P.O. "
      #define STR0041 " de "
      #define STR0042 "Nr. P.O.:"
      #define STR0043 "Data: "
      #define STR0044 "Forn:"
      #define STR0045 "Total Fob: "
      #define STR0046 "Todos"
      #define STR0047 "Pesquisa de Itens"
      #define STR0048 "Processando Item "
      #define STR0049 "REGERANDO ARQUIVO DE TRABALHO"
      #define STR0050 "Lendo Itens do P.O. "
      #define STR0051 "Sele‡ao de S.I."
      #define STR0052 "C.C."
      #define STR0053 'S.I. N§'
      #define STR0054 '(F3-Help)'
      #define STR0055 '(F4-Help)'
      #define STR0056 "Deseja Sair?"
      #define STR0057 "Confirmação de Saída"
      #define STR0058 "Descri‡ao em Inglˆs"
      #define STR0059 "Nome"
      #define STR0060 "Unidade"
      #define STR0061 "Sele‡Æo de Itens"
      #define STR0062 "Pesquisa/P.N."
      #define STR0063 "Troca S.I."
      #define STR0064 "Conferencia"
      #define STR0065 'S.I. N§ '
      #define STR0066 "Fornecedor deve ser o mesmo j  informado ! ("
      #define STR0067 "Informação"
      #define STR0068 " (COM ANUENCIA PREVIA)"
      #define STR0069 " (SEM ANUENCIA PREVIA)"
      #define STR0070 "Dados do Item"
      #define STR0071 'C¢digo Item'
      #define STR0072 'Fabricante'
      #define STR0073 'Anuencia ?'
      #define STR0074 'Saldo Qtde'
      #define STR0075 'Reg. Ministerio'
      #define STR0076 'Embarcado'
      #define STR0077 'Pre‡o Unit rio'
      #define STR0078 'Custo Total'
      #define STR0079 'Embarque'
      #define STR0080 'Entrega'
      #define STR0081 'Outros C¢digos de Fabricante (Endere‡os p/ L.I.)'
      #define STR0082 "(F4-Help)"
      #define STR0083 "N§ S.I."
      #define STR0084 "Pre‡o Unit rio"
      #define STR0085 "Pre‡o Total"
      #define STR0086 "Conferˆncia Final"
      #define STR0087 "Nr. P.O.: "
      #define STR0088 "Data.: "
      #define STR0089 "Alteracao "
      #define STR0090 "Fob Total "
      #define STR0091 "Grava P.O."
      #define STR0092 "Alt.Datas"
      #define STR0093 ' da solicitação não informado'
      #define STR0094 " não cadastrado"
      #define STR0095 'N£mero da solicita‡Æo nÆo informado'
      #define STR0096 'Solicitação não cadastrada'
      #define STR0097 "Moeda da Solicita‡Æo ‚ diferente da moeda do Pedido."
      #define STR0098 "Pesquisando Itens da S.I."
      #define STR0099 'NÆo h  itens desta solicita‡Æo a serem selecionados'
      #define STR0100 ", pois P.O. foi Incluso por Integra‡Æo"
      #define STR0101 "Processando Item: "
      #define STR0102 "Itens com valor unit rio Zerado"
      #define STR0103 "Desconto não pode ser maior que F.O.B + INLAND + PACKING "
      #define STR0104 "+ FRETE"
      #define STR0105 'Fechamento'
      #define STR0106 "Gerando Posicoes"
      #define STR0107 "Gravacao do P.O."
      #define STR0108 "O N£mero do Pedido da Micro Siga ‚ : "
      #define STR0109 "O N£mero do Pedido ‚ : "
      #define STR0110 "Gravando Posicao do Item: "
      #define STR0111 "C¢digo N.C.M. nÆo cadastrado"
      #define STR0112 "C¢digos N.C.M.s nÆo cadastrado"
      #define STR0113 "C¢digos N.C.M.s e N.B.M. nÆo cadastrados"
      #define STR0114 "Tipo de Frete Difere de (PP-Prepaid / CC-Collect)"
      #define STR0115 "Tipo de Frete não pode ser Alterado, pois P.O. possui L.I"
      #define STR0116 "Este campo não pode ser preenchido na Inclusão"
      #define STR0117 'Item '
      #define STR0118 ' não cadastrado para o Fabr. '
      #define STR0119 ' / Forn. '
      #define STR0120 "Fornecedor não preenchido"
      #define STR0121 "Fornecedor não cadastrado"
      #define STR0122 "Registro cadastrado como fabricante"
      #define STR0123 "Cliente não encontrado"
      #define STR0124 "Atenção - Número da cotação não cadastrado"
      #define STR0125 'Condição de Pagamento não preenchida '
      #define STR0126 'Condição não pode ser Alterada, pois P.O. possui L.I.'
      #define STR0127 'Condição nÆo Cadastrada'
      #define STR0128 "Verificando Itens do P.O."
      #define STR0129 'Condição não Cadastrada'
      #define STR0130 "Dias Pagto não pode ser Alterado, pois P.O. possui L.I."
      #define STR0131 'Dias de pagamento não cadastrado'
      #define STR0132 "N„o existe esta Via de Transporte / Origem / Destino no Cadastro de Fretes"
      #define STR0133 "N„o existe esta Via de Transporte / Origem no Cadastro de Fretes"
      #define STR0134 "Incoterms não pode ser Alterado - P.O. possui L.I."
      #define STR0135 'N£mero de portaria diferente de 0,7/8,15'
      #define STR0136 "Moeda não pode ser alterada - P.O. possui LI"
      #define STR0137 'Não existe cotação para esta moeda'
      #define STR0138 'Saldo da quantidade não preenchido'
      #define STR0139 'Saldo da quantidade não pode ser negativo'
      #define STR0140 'Quantidade maior que o saldo da solicitação'
      #define STR0141 'Valor unit rio nÆo preenchido'
      #define STR0142 'Valor unit rio nÆo pode ser negativo'
      #define STR0143 'Código '
      #define STR0144 ' não cadastrado'
      #define STR0145 'Data de embarque deve ser maior que a data do P.O.'
      #define STR0146 'Data de entrega deve ser maior ou igual que a data de embarque'
      #define STR0147 ' não cadastrado p/ o fabr. '
      #define STR0148 ' e forn. '
      #define STR0149 'Data de entrega menor que o lead time operacional'
      #define STR0150 'Data de entrega menor que o lead time do item'
      #define STR0151 "Importador não pode ser alterado - P.O. possui L.I."
      #define STR0152 'Código do importador não preenchido'
      #define STR0153 'Código do importador não cadastrado'
      #define STR0154 "Código informado não é de importador"
      #define STR0155 "Consignatário não pode ser alterado - P.O. possui L.I."
      #define STR0156 'Código do consignatário não cadastrado'
      #define STR0157 "Código informado não é de consignatário"
      #define STR0158 "Caracter diferente de 'S-Sim' / 'N-Nao'"
      #define STR0159 "Esta informação não pode ser alterada, o item já possui L.I., estorne-a."
      #define STR0160 "Item já tem qtde.embarcada,não pode ser alterado p/ com anuência."
      #define STR0161 "C¢digo de observa‡Æo inexistente"
      #define STR0162 "Exportador não cadastrado"
      #define STR0163 "Tipo da comissão não pode ser preenchido"
      #define STR0164 "Tipo da comissão não preenchido"
      #define STR0165 "Valor da comissão não pode ser preenchido"
      #define STR0166 "Valor da comissão não preenchido"
      #define STR0167 "Percentual da comissão não pode ser preenchido"
      #define STR0168 "Percentual da comissão não preenchido"
      #define STR0169 "Outr. Comis. não pode ser preenchido"
      #define STR0170 "Outr. Comis. não preenchido"
      #define STR0171 "Volume cubado não pode ser negativo"
      #define STR0172 "Container de 20' não pode ser negativo"
      #define STR0173 "Container de 40' não pode ser negativo"
      #define STR0174 "Container de 40' HC não pode ser negativo"
      #define STR0175 "Outros não pode ser negativo"
      #define STR0176 "Processando Item nr. "
      #define STR0177 'Fabricante não cadastrado para este item'
      #define STR0178 "Despesas"
      #define STR0179 "incluir get despesas na alteracao"
      #define STR0180 "Inland Charge"
      #define STR0181 "Packing Charge"
      #define STR0182 "Int'l Freight"
      #define STR0183 "Desconto"
      #define STR0184 "Confirma o "
      #define STR0185 " deste P.O. ? "
      #define STR0186 "Confirmação"
      #define STR0187 "Estorno em andamento..."
      #define STR0188 "Estornando UR: "
      #define STR0189 " SI: "
      #define STR0190 " Item: "
      #define STR0191 "Processando Ocorrencias"
      #define STR0192 'ESTORNO DO P.O. - '
      #define STR0193 'TOTAL'
      #define STR0194 'SALDO'
      #define STR0195 "PO"
      #define STR0196 "Criando Arquivo"
      #define STR0197 "Criando Indice 1"
      #define STR0198 "Processando Arquivo Temporário..."
      #define STR0199 "Criando Indice 2"
      #define STR0200 "Processando Arquivo Temporario..."
      #define STR0201 "Codigo"
      #define STR0202 "Gerando Help de Fabricantes"
      #define STR0203 "Consulta Itens/Fabricantes"
      #define STR0204 "Processando Fabricante nr. "
      #define STR0205 "No da S.I."
      #define STR0206 "Gerando Help de S.I."
      #define STR0207 "Consulta "
      #define STR0208 " da S.I."
      #define STR0209 "Processando S.I. nr. "
      #define STR0210 "Data de entrega sugerida não preenchida."
      #define STR0211 "Data de embarque sugerida não preenchida."
      #define STR0212 'Alteracao de Datas'
      #define STR0213 "Data Embarque"
      #define STR0214 "Previsao de Entrega"
      #define STR0215 "De:                          Para:"
      #define STR0216 "De:                            Para:"
      #define STR0217 "A previsão de entrega deve ser maior que a de embarque."
      #define STR0218 "Confirma estas datas para os itens ?"
      #define STR0219 "Gravando Registro No "
      #define STR0220 "Gerando Arquivos de Trabalho..."
   #ELSE
      #define STR0001 "Função não autorizada para este módulo !"
      #define STR0002 "Aviso"
      #define STR0003 "Pesquisar"
      #define STR0004 "Visual"
      #define STR0005 "Inclui"
      #define STR0006 "Altera"
      #define STR0007 "Estorna"
      #define STR0008 "Purchase Order"
      #define STR0009 "Estorno"
      #define STR0010 '   Anuencia    '
      #define STR0011 "No.SI"
      #define STR0012 "Posicao"
      #define STR0013 "Item"
      #define STR0014 "Part Number"
      #define STR0015 'Nao'
      #define STR0016 'Sim'
      #define STR0017 "Anuencia"
      #define STR0018 "Descricao em Ingles"
      #define STR0019 "Fabricante"
      #define STR0020 "Uni"
      #define STR0021 "Vlr. Total Midia"
      #define STR0022 "Quantidade"
      #define STR0023 "Qtde Embarcada"
      #define STR0024 "Saldo Qtde"
      #define STR0025 "Preco Unit"
      #define STR0026 "Valor Total"
      #define STR0027 "Embarque"
      #define STR0028 "Entrega"
      #define STR0029 "Sim"
      #define STR0030 "Nao"
      #define STR0031 "Forecast"
      #define STR0032 "Registro no Minist‚rio / OrgÆo P£blico"
      #define STR0033 "Salva & Sai"
      #define STR0034 'Confirma a Gravação ? '
      #define STR0035 'Capa do P.O.'
      #define STR0036 "Pedido não pode ser estornado, pois possui processo em andamento."
      #define STR0037 "Atenção"
      #define STR0038 "N§ SI"
      #define STR0039 "Preco"
      #define STR0040 "P.O. "
      #define STR0041 " de "
      #define STR0042 "Nr. P.O.:"
      #define STR0043 "Data: "
      #define STR0044 "Forn:"
      #define STR0045 "Total Fob: "
      #define STR0046 "Todos"
      #define STR0047 "Pesquisa de Itens"
      #define STR0048 "Processando Item "
      #define STR0049 "REGERANDO ARQUIVO DE TRABALHO"
      #define STR0050 "Lendo Itens do P.O. "
      #define STR0051 "Sele‡ao de S.I."
      #define STR0052 "C.C."
      #define STR0053 'S.I. N§'
      #define STR0054 '(F3-Help)'
      #define STR0055 '(F4-Help)'
      #define STR0056 "Deseja Sair?"
      #define STR0057 "Confirmação de Saída"
      #define STR0058 "Descri‡ao em Inglˆs"
      #define STR0059 "Nome"
      #define STR0060 "Unidade"
      #define STR0061 "Sele‡Æo de Itens"
      #define STR0062 "Pesquisa/P.N."
      #define STR0063 "Troca S.I."
      #define STR0064 "Conferencia"
      #define STR0065 'S.I. N§ '
      #define STR0066 "Fornecedor deve ser o mesmo j  informado ! ("
      #define STR0067 "Informação"
      #define STR0068 " (COM ANUENCIA PREVIA)"
      #define STR0069 " (SEM ANUENCIA PREVIA)"
      #define STR0070 "Dados do Item"
      #define STR0071 'C¢digo Item'
      #define STR0072 'Fabricante'
      #define STR0073 'Anuencia ?'
      #define STR0074 'Saldo Qtde'
      #define STR0075 'Reg. Ministerio'
      #define STR0076 'Embarcado'
      #define STR0077 'Pre‡o Unit rio'
      #define STR0078 'Custo Total'
      #define STR0079 'Embarque'
      #define STR0080 'Entrega'
      #define STR0081 'Outros C¢digos de Fabricante (Endere‡os p/ L.I.)'
      #define STR0082 "(F4-Help)"
      #define STR0083 "N§ S.I."
      #define STR0084 "Pre‡o Unit rio"
      #define STR0085 "Pre‡o Total"
      #define STR0086 "Conferˆncia Final"
      #define STR0087 "Nr. P.O.: "
      #define STR0088 "Data.: "
      #define STR0089 "Alteracao "
      #define STR0090 "Fob Total "
      #define STR0091 "Grava P.O."
      #define STR0092 "Alt.Datas"
      #define STR0093 ' da solicitação não informado'
      #define STR0094 " não cadastrado"
      #define STR0095 'N£mero da solicita‡Æo nÆo informado'
      #define STR0096 'Solicitação não cadastrada'
      #define STR0097 "Moeda da Solicita‡Æo ‚ diferente da moeda do Pedido."
      #define STR0098 "Pesquisando Itens da S.I."
      #define STR0099 'NÆo h  itens desta solicita‡Æo a serem selecionados'
      #define STR0100 ", pois P.O. foi Incluso por Integra‡Æo"
      #define STR0101 "Processando Item: "
      #define STR0102 "Itens com valor unit rio Zerado"
      #define STR0103 "Desconto não pode ser maior que F.O.B + INLAND + PACKING "
      #define STR0104 "+ FRETE"
      #define STR0105 'Fechamento'
      #define STR0106 "Gerando Posicoes"
      #define STR0107 "Gravacao do P.O."
      #define STR0108 "O N£mero do Pedido da Micro Siga ‚ : "
      #define STR0109 "O N£mero do Pedido ‚ : "
      #define STR0110 "Gravando Posicao do Item: "
      #define STR0111 "C¢digo N.C.M. nÆo cadastrado"
      #define STR0112 "C¢digos N.C.M.s nÆo cadastrado"
      #define STR0113 "C¢digos N.C.M.s e N.B.M. nÆo cadastrados"
      #define STR0114 "Tipo de Frete Difere de (PP-Prepaid / CC-Collect)"
      #define STR0115 "Tipo de Frete não pode ser Alterado, pois P.O. possui L.I"
      #define STR0116 "Este campo não pode ser preenchido na Inclusão"
      #define STR0117 'Item '
      #define STR0118 ' não cadastrado para o Fabr. '
      #define STR0119 ' / Forn. '
      #define STR0120 "Fornecedor não preenchido"
      #define STR0121 "Fornecedor não cadastrado"
      #define STR0122 "Registro cadastrado como fabricante"
      #define STR0123 "Cliente não encontrado"
      #define STR0124 "Atenção - Número da cotação não cadastrado"
      #define STR0125 'Condição de Pagamento não preenchida '
      #define STR0126 'Condição não pode ser Alterada, pois P.O. possui L.I.'
      #define STR0127 'Condição nÆo Cadastrada'
      #define STR0128 "Verificando Itens do P.O."
      #define STR0129 'Condição não Cadastrada'
      #define STR0130 "Dias Pagto não pode ser Alterado, pois P.O. possui L.I."
      #define STR0131 'Dias de pagamento não cadastrado'
      #define STR0132 "N„o existe esta Via de Transporte / Origem / Destino no Cadastro de Fretes"
      #define STR0133 "N„o existe esta Via de Transporte / Origem no Cadastro de Fretes"
      #define STR0134 "Incoterms não pode ser Alterado - P.O. possui L.I."
      #define STR0135 'N£mero de portaria diferente de 0,7/8,15'
      #define STR0136 "Moeda não pode ser alterada - P.O. possui LI"
      #define STR0137 'Não existe cotação para esta moeda'
      #define STR0138 'Saldo da quantidade não preenchido'
      #define STR0139 'Saldo da quantidade não pode ser negativo'
      #define STR0140 'Quantidade maior que o saldo da solicitação'
      #define STR0141 'Valor unit rio nÆo preenchido'
      #define STR0142 'Valor unit rio nÆo pode ser negativo'
      #define STR0143 'Código '
      #define STR0144 ' não cadastrado'
      #define STR0145 'Data de embarque deve ser maior que a data do P.O.'
      #define STR0146 'Data de entrega deve ser maior ou igual que a data de embarque'
      #define STR0147 ' não cadastrado p/ o fabr. '
      #define STR0148 ' e forn. '
      #define STR0149 'Data de entrega menor que o lead time operacional'
      #define STR0150 'Data de entrega menor que o lead time do item'
      #define STR0151 "Importador não pode ser alterado - P.O. possui L.I."
      #define STR0152 'Código do importador não preenchido'
      #define STR0153 'Código do importador não cadastrado'
      #define STR0154 "Código informado não é de importador"
      #define STR0155 "Consignatário não pode ser alterado - P.O. possui L.I."
      #define STR0156 'Código do consignatário não cadastrado'
      #define STR0157 "Código informado não é de consignatário"
      #define STR0158 "Caracter diferente de 'S-Sim' / 'N-Nao'"
      #define STR0159 "Esta informação não pode ser alterada, o item já possui L.I., estorne-a."
      #define STR0160 "Item já tem qtde.embarcada,não pode ser alterado p/ com anuência."
      #define STR0161 "C¢digo de observa‡Æo inexistente"
      #define STR0162 "Exportador não cadastrado"
      #define STR0163 "Tipo da comissão não pode ser preenchido"
      #define STR0164 "Tipo da comissão não preenchido"
      #define STR0165 "Valor da comissão não pode ser preenchido"
      #define STR0166 "Valor da comissão não preenchido"
      #define STR0167 "Percentual da comissão não pode ser preenchido"
      #define STR0168 "Percentual da comissão não preenchido"
      #define STR0169 "Outr. Comis. não pode ser preenchido"
      #define STR0170 "Outr. Comis. não preenchido"
      #define STR0171 "Volume cubado não pode ser negativo"
      #define STR0172 "Container de 20' não pode ser negativo"
      #define STR0173 "Container de 40' não pode ser negativo"
      #define STR0174 "Container de 40' HC não pode ser negativo"
      #define STR0175 "Outros não pode ser negativo"
      #define STR0176 "Processando Item nr. "
      #define STR0177 'Fabricante não cadastrado para este item'
      #define STR0178 "Despesas"
      #define STR0179 "incluir get despesas na alteracao"
      #define STR0180 "Inland Charge"
      #define STR0181 "Packing Charge"
      #define STR0182 "Int'l Freight"
      #define STR0183 "Desconto"
      #define STR0184 "Confirma o "
      #define STR0185 " deste P.O. ? "
      #define STR0186 "Confirmação"
      #define STR0187 "Estorno em andamento..."
      #define STR0188 "Estornando UR: "
      #define STR0189 " SI: "
      #define STR0190 " Item: "
      #define STR0191 "Processando Ocorrencias"
      #define STR0192 'ESTORNO DO P.O. - '
      #define STR0193 'TOTAL'
      #define STR0194 'SALDO'
      #define STR0195 "PO"
      #define STR0196 "Criando Arquivo"
      #define STR0197 "Criando Indice 1"
      #define STR0198 "Processando Arquivo Temporário..."
      #define STR0199 "Criando Indice 2"
      #define STR0200 "Processando Arquivo Temporario..."
      #define STR0201 "Codigo"
      #define STR0202 "Gerando Help de Fabricantes"
      #define STR0203 "Consulta Itens/Fabricantes"
      #define STR0204 "Processando Fabricante nr. "
      #define STR0205 "No da S.I."
      #define STR0206 "Gerando Help de S.I."
      #define STR0207 "Consulta "
      #define STR0208 " da S.I."
      #define STR0209 "Processando S.I. nr. "
      #define STR0210 "Data de entrega sugerida não preenchida."
      #define STR0211 "Data de embarque sugerida não preenchida."
      #define STR0212 'Alteracao de Datas'
      #define STR0213 "Data Embarque"
      #define STR0214 "Previsao de Entrega"
      #define STR0215 "De:                          Para:"
      #define STR0216 "De:                            Para:"
      #define STR0217 "A previsão de entrega deve ser maior que a de embarque."
      #define STR0218 "Confirma estas datas para os itens ?"
      #define STR0219 "Gravando Registro No "
      #define STR0220 "Gerando Arquivos de Trabalho..."
   #ENDIF
#ENDIF
