#IFDEF SPANISH
   #define STR0001 "&Buscar"
   #define STR0002 "&Visualizar"
   #define STR0003 "&Incluir"
   #define STR0004 "Modific&Ar"
   #define STR0005 "&Borrar"
   #define STR0006 "Eva&luar"
   #define STR0007 "Cotizacion de Precios"
   #define STR0008 "Cuadro de Competidores"
   #define STR0009 "Cuadro de Competidores - "
   #define STR0010 "Producto"
   #define STR0011 "Descripcion"
   #define STR0012 "Cantidad"
   #define STR0013 "Peso Total "
   #define STR0014 "C.C."
   #define STR0015 "S.I."
   #define STR0016 "Fc.Prev."
   #define STR0017 "Cod. Prov."
   #define STR0018 "Proveedor"
   #define STR0019 "Part Number"
   #define STR0020 "Origen"
   #define STR0021 "Moneda FOB"
   #define STR0022 "FOB Unit."
   #define STR0023 "Moneda Flete"
   #define STR0024 "Flete Total"
   #define STR0025 "Seguro"
   #define STR0026 "Fc Ult Compra"
   #define STR0027 "Vr Ultima Compra"
   #define STR0028 "FOB Total"
   #define STR0029 "Fecha Entr."
   #define STR0030 "Cod. Fabr."
   #define STR0031 "Fabricante"
   #define STR0032 "Procesando Registros de Competidores"
   #define STR0033 "Items"
   #define STR0034 "Proveedores"
   #define STR0035 "Item de Competidores "
   #define STR0036 "Proveedor del Item "
   #define STR0037 " - Inclusion"
   #define STR0038 " - Modificacion"
   #define STR0039 "No hay item para incluir Proveedores"
   #define STR0040 "Aviso"
   #define STR0041 "Medio de Transporte no llenado"
   #define STR0042 "Procesando Proveedores del Item "
   #define STR0043 " - Visualizar"
   #define STR0044 " - Borrado"
   #define STR0045 "Competidores no pueden ser grabados sin items"
   #define STR0046 "Grabando Informaciones de los Competidores"
   #define STR0047 "Borrando Registros"
   #define STR0048 "No hay Registros para la opcion"
   #define STR0049 "Grabando Items de S.I."
   #define STR0050 '®Confirma Borrado? '
   #define STR0051 'Borrar'
   #define STR0052 "Procesando Registros"
   #define STR0053 "Actualizando Items de Competidores"
   #define STR0054 "Actualizando Proveedores de los Items"
   #define STR0055 "Grabando Items de los Competidores"
   #define STR0056 "Grabando Proveedores de los Items"
   #define STR0057 "Grabando S.I. Nro "
   #define STR0058 "No hay saldos para esta S.I."
   #define STR0059 "Atencion"
   #define STR0060 "®Acumular cantidad de Producto "
   #define STR0061 " que ya existe?"
   #define STR0062 "Cantidades "
   #define STR0063 "Procesando Item "
   #define STR0064 "Procesando Proveedor "
   #define STR0065 "Borrando Item "
   #define STR0066 'Numero de S.I. no llenado '
   #define STR0067 "Unidad Requirente no llenada"
   #define STR0068 "S.I. no archivada para esa Unidad Requisitante"
   #define STR0069 "Informacion"
   #define STR0070 "Procesando Archivo Temporal..."
   #define STR0071 'Solicitud ya archivada para esta Cotizacion'
   #define STR0072 'Codigo del Producto no llenado'
   #define STR0073 'Producto no encontrado en el archivo'
   #define STR0074 'Producto ya archivado para esta Cotizacion'
   #define STR0075 'Cantidad no Llenada'
   #define STR0076 'Fecha de Necesidad no llenada'
   #define STR0077 'Fecha de Necesidad menor que la fecha de Hoy'
   #define STR0078 'Proveedor no llenado'
   #define STR0079 "Proveedor no archivado"
   #define STR0080 'Codigo no se refiere a Proveedor'
   #define STR0081 'Proveedor ya archivado p/la Cotizacion de este Producto'
   #define STR0082 "Fabricante no archivado"
   #define STR0083 'Codigo no se refiere a Fabricante'
   #define STR0084 'Origen no llenada'
   #define STR0085 'Origen no archivada para este Medio y Destino'
   #define STR0086 'FOB Unitario no llenado'
   #define STR0087 'Valor de Flete no debe ser llenado ( Pre-Paid )'
   #define STR0088 'Flete no llenado'
   #define STR0089 'Condicion de Pago no llenada'
   #define STR0090 'Condicion de Pago no Archivada'
   #define STR0091 'Moneda del Fob no llenada'
   #define STR0092 'Moneda del Fob sin tasa de conversion'
   #define STR0093 'Codigo no llenado'
   #define STR0094 'Codigo no archivado'
   #define STR0095 'Proveedor no archivado en esta Competencia'
   #define STR0096 'FOB Unitario no puede ser negativo'
   #define STR0097 "Unidad Requirente no archivada"
   #define STR0098 "U.R. no pertenece a esa Cotizacion"
   #define STR0099 "S.I. no pertenece a esa Cotizacion"
   #define STR0100 "Unidad Requirente no pertenece a esa Competencia"
   #define STR0101 "S.I. no pertenece a esa Competencia"
   #define STR0102 "Calculadora"
   #define STR0103 "Help de Programa"
   #define STR0104 "Impresion"
   #define STR0105 "Inclusion"
   #define STR0106 "Modificacion"
   #define STR0107 "Borrado"
   #define STR0108 "Items\Prov."
   #define STR0109 "Anular - <Ctrl-X>"
   #define STR0110 "Evaluacion del Cuadro de Competencia"
   #define STR0111 "Cod. Prod."
   #define STR0112 "Clas"
   #define STR0113 "FOB Unitario"
   #define STR0114 "Vl. C.I.F."
   #define STR0115 "% Var"
   #define STR0116 "Cond Pago"
   #define STR0117 "Procesando Items de la Cotizacion"
   #define STR0118 "1 - Por Valor CIF"
   #define STR0119 "2 - Por Valor FOB Total"
   #define STR0120 "3 - Por Fecha de Entrega"
   #define STR0121 "Seleccion de la Evaluacion"
   #define STR0122 "Unidad Requ."
   #define STR0123 "S.I. Nro."
   #define STR0124 "Tipo de Computo"
   #define STR0125 "Consulta U.R. de Cotizacion: "
   #define STR0126 "Consulta S.I. de Cotizacion: "
   #define STR0127 "Procesando Item Nro: "
   #define STR0128 "Clasificando Item Nro: "
   #define STR0129 "Items del Proveedor..."
   #define STR0130 "Codigo del Proveedor "
   #define STR0131 "Items del Proveedor: "
   #define STR0132 "Modificar FOB Unitario"
   #define STR0133 "Graba"
   #define STR0134 "Salir"
   #define STR0135 "FOB Unitario del Item: "
   #define STR0136 "Nuevo"
   #define STR0137 "Actual"
   #define STR0138 "FOB Unitario"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "&Pesquisar"
      #define STR0002 "&Visual"
      #define STR0003 "&Inclui"
      #define STR0004 "&Altera"
      #define STR0005 "&Exclui"
      #define STR0006 "Ava&lia"
      #define STR0007 "Cotaá∆o de Precos"
      #define STR0008 "Quadro de Concorrància"
      #define STR0009 "Quadro de Concorrància - "
      #define STR0010 "Produto"
      #define STR0011 "DescriÁ„o"
      #define STR0012 "Quantidade"
      #define STR0013 "Peso Total "
      #define STR0014 "C.C."
      #define STR0015 "S.I."
      #define STR0016 "Dt.Prev."
      #define STR0017 "Cod. Forn."
      #define STR0018 "Fornecedor"
      #define STR0019 "Part Number"
      #define STR0020 "Origem"
      #define STR0021 "Moeda FOB"
      #define STR0022 "FOB Unit."
      #define STR0023 "Moeda Frete"
      #define STR0024 "Frete Total"
      #define STR0025 "Seguro"
      #define STR0026 "Dt Ult Compra"
      #define STR0027 "Vr Ultima Compra"
      #define STR0028 "FOB Total"
      #define STR0029 "Data Entr."
      #define STR0030 "Cod. Fabr."
      #define STR0031 "Fabricante"
      #define STR0032 "Processando Registros da Concorrencia"
      #define STR0033 "Itens"
      #define STR0034 "Fornecedores"
      #define STR0035 "Item da Concorrància "
      #define STR0036 "Fornecedor do Item "
      #define STR0037 " - Inclus„o"
      #define STR0038 " - AlteraÁ„o"
      #define STR0039 "N∆o existe item para incluir Fornecedores"
      #define STR0040 "Aviso"
      #define STR0041 "Via de Transporte n∆o preenchida"
      #define STR0042 "Processando Fornecedores do Item "
      #define STR0043 " - Visualisar"
      #define STR0044 " - Exclus„o"
      #define STR0045 "Concorrància n∆o pode ser gravada sem itens"
      #define STR0046 "Gravando Informacoes da Concorrencia"
      #define STR0047 "Excluindo Registros"
      #define STR0048 "N∆o existe Registros para a opá∆o"
      #define STR0049 "Gravando Itens da S.I."
      #define STR0050 'Confirma Exclus„o ? '
      #define STR0051 'Excluir'
      #define STR0052 "Processando Registros"
      #define STR0053 "Atualizando Itens da Concorrencia"
      #define STR0054 "Atualizando Fornecedores dos Itens"
      #define STR0055 "Gravando Itens da Concorrencia"
      #define STR0056 "Gravando Fornecedores dos Itens"
      #define STR0057 "Gravando S.I. No "
      #define STR0058 "N∆o h† saldos para esta S.I."
      #define STR0059 "AtenÁ„o"
      #define STR0060 "Acumular quantidade do Produto "
      #define STR0061 " que j† existe  ?"
      #define STR0062 "Quantidades "
      #define STR0063 "Processando Item "
      #define STR0064 "Processando Fornecedor "
      #define STR0065 "Excluindo Item "
      #define STR0066 'N£mero da S.I. n∆o preenchido '
      #define STR0067 "Unidade Requisitante n„o preenchida"
      #define STR0068 "S.I. n„o cadastrada para essa Unidade Requisitante"
      #define STR0069 "InformaÁ„o"
      #define STR0070 "Processando Arquivo Tempor·rio..."
      #define STR0071 'Solicitaá∆o j† cadastrada para esta Cotaá∆o'
      #define STR0072 'C¢digo do Produto n∆o preenchido'
      #define STR0073 'Produto n„o encontrado no cadastro'
      #define STR0074 'Produto j† cadastrado para esta Cotaá∆o'
      #define STR0075 'Quantidade n„o Preenchida'
      #define STR0076 'Data da Necessidade nÁ„o preenchida'
      #define STR0077 'Data da Necessidade menor que a data de Hoje'
      #define STR0078 'Fornecedor n„o preenchido'
      #define STR0079 "Fornecedor n„o cadastrado"
      #define STR0080 'C¢digo n∆o se refere a Fornecedor'
      #define STR0081 'Fornecedor j† cadastrado p/ a Cotaá∆o deste Produto'
      #define STR0082 "Fabricante n„o cadastrado"
      #define STR0083 'C¢digo n∆o se refere a Fabricante'
      #define STR0084 'Origem n„o preenchida'
      #define STR0085 'Origem n„o cadastrada para esta Via e Destino'
      #define STR0086 'FOB Unit†rio n∆o preenchido'
      #define STR0087 'Valor de Frete n∆o deve ser preenchido ( Pre-Paid )'
      #define STR0088 'Frete n∆o preenchido'
      #define STR0089 'CondiÁ„o de Pagamento n„o preenchida'
      #define STR0090 'CondiÁ„o de Pagamento n„o Cadastrada'
      #define STR0091 'Moeda do Fob n„o preenchida'
      #define STR0092 'Moeda do Fob sem taxa de convers„o'
      #define STR0093 'C¢digo n∆o preenchido'
      #define STR0094 'C¢digo n∆o cadastrado'
      #define STR0095 'Fornecedor n∆o cadastrado nesta Concorrància'
      #define STR0096 'FOB Unit†rio n∆o pode ser negativo'
      #define STR0097 "Unidade Requisitante n„o cadastrada"
      #define STR0098 "U.R. n„o pertence a essa CotaÁ„o"
      #define STR0099 "S.I. n„o pertence a essa CotaÁ„o"
      #define STR0100 "Unidade Requisitante n∆o pertence a essa Concorrància"
      #define STR0101 "S.I. n∆o pertence a essa Concorrància"
      #define STR0102 "Calculadora"
      #define STR0103 "Help de Programa"
      #define STR0104 "Impress∆o"
      #define STR0105 "Inclus„o"
      #define STR0106 "AlteraÁ„o"
      #define STR0107 "Exclus„o"
      #define STR0108 "Itens\Forn."
      #define STR0109 "Cancelar - <Ctrl-X>"
      #define STR0110 "Avaliaá∆o do Quadro de Concorrància"
      #define STR0111 "Cod. Prod."
      #define STR0112 "Class"
      #define STR0113 "FOB Unitario"
      #define STR0114 "Vl. C.I.F."
      #define STR0115 "% Var"
      #define STR0116 "Cond Pagto"
      #define STR0117 "Processando Itens da CotaÁ„o"
      #define STR0118 "1 - Por Valor CIF"
      #define STR0119 "2 - Por Valor FOB Total"
      #define STR0120 "3 - Por Data de Entrega"
      #define STR0121 "Seleá∆o da Avaliaá∆o"
      #define STR0122 "Unidade Requ."
      #define STR0123 "S.I. Nß"
      #define STR0124 "Tipo de Apuraá∆o"
      #define STR0125 "Consulta U.R. da Cotaá∆o: "
      #define STR0126 "Consulta S.I. da Cotaá∆o: "
      #define STR0127 "Processando Item No: "
      #define STR0128 "Classificando Item No: "
      #define STR0129 "Itens do Fornecedor..."
      #define STR0130 "C¢digo do Fornecedor "
      #define STR0131 "Itens do Fornecedor: "
      #define STR0132 "Alterar FOB Unit†rio"
      #define STR0133 "Grava"
      #define STR0134 "Sair"
      #define STR0135 "FOB Unit†rio do Item: "
      #define STR0136 "Novo"
      #define STR0137 "Atual"
      #define STR0138 "FOB Unit†rio"
   #ELSE
      #define STR0001 "&Pesquisar"
      #define STR0002 "&Visual"
      #define STR0003 "&Inclui"
      #define STR0004 "&Altera"
      #define STR0005 "&Exclui"
      #define STR0006 "Ava&lia"
      #define STR0007 "Cotaá∆o de Precos"
      #define STR0008 "Quadro de Concorrància"
      #define STR0009 "Quadro de Concorrància - "
      #define STR0010 "Produto"
      #define STR0011 "DescriÁ„o"
      #define STR0012 "Quantidade"
      #define STR0013 "Peso Total "
      #define STR0014 "C.C."
      #define STR0015 "S.I."
      #define STR0016 "Dt.Prev."
      #define STR0017 "Cod. Forn."
      #define STR0018 "Fornecedor"
      #define STR0019 "Part Number"
      #define STR0020 "Origem"
      #define STR0021 "Moeda FOB"
      #define STR0022 "FOB Unit."
      #define STR0023 "Moeda Frete"
      #define STR0024 "Frete Total"
      #define STR0025 "Seguro"
      #define STR0026 "Dt Ult Compra"
      #define STR0027 "Vr Ultima Compra"
      #define STR0028 "FOB Total"
      #define STR0029 "Data Entr."
      #define STR0030 "Cod. Fabr."
      #define STR0031 "Fabricante"
      #define STR0032 "Processando Registros da Concorrencia"
      #define STR0033 "Itens"
      #define STR0034 "Fornecedores"
      #define STR0035 "Item da Concorrància "
      #define STR0036 "Fornecedor do Item "
      #define STR0037 " - Inclus„o"
      #define STR0038 " - AlteraÁ„o"
      #define STR0039 "N∆o existe item para incluir Fornecedores"
      #define STR0040 "Aviso"
      #define STR0041 "Via de Transporte n∆o preenchida"
      #define STR0042 "Processando Fornecedores do Item "
      #define STR0043 " - Visualisar"
      #define STR0044 " - Exclus„o"
      #define STR0045 "Concorrància n∆o pode ser gravada sem itens"
      #define STR0046 "Gravando Informacoes da Concorrencia"
      #define STR0047 "Excluindo Registros"
      #define STR0048 "N∆o existe Registros para a opá∆o"
      #define STR0049 "Gravando Itens da S.I."
      #define STR0050 'Confirma Exclus„o ? '
      #define STR0051 'Excluir'
      #define STR0052 "Processando Registros"
      #define STR0053 "Atualizando Itens da Concorrencia"
      #define STR0054 "Atualizando Fornecedores dos Itens"
      #define STR0055 "Gravando Itens da Concorrencia"
      #define STR0056 "Gravando Fornecedores dos Itens"
      #define STR0057 "Gravando S.I. No "
      #define STR0058 "N∆o h† saldos para esta S.I."
      #define STR0059 "AtenÁ„o"
      #define STR0060 "Acumular quantidade do Produto "
      #define STR0061 " que j† existe  ?"
      #define STR0062 "Quantidades "
      #define STR0063 "Processando Item "
      #define STR0064 "Processando Fornecedor "
      #define STR0065 "Excluindo Item "
      #define STR0066 'N£mero da S.I. n∆o preenchido '
      #define STR0067 "Unidade Requisitante n„o preenchida"
      #define STR0068 "S.I. n„o cadastrada para essa Unidade Requisitante"
      #define STR0069 "InformaÁ„o"
      #define STR0070 "Processando Arquivo Tempor·rio..."
      #define STR0071 'Solicitaá∆o j† cadastrada para esta Cotaá∆o'
      #define STR0072 'C¢digo do Produto n∆o preenchido'
      #define STR0073 'Produto n„o encontrado no cadastro'
      #define STR0074 'Produto j† cadastrado para esta Cotaá∆o'
      #define STR0075 'Quantidade n„o Preenchida'
      #define STR0076 'Data da Necessidade n„o preenchida'
      #define STR0077 'Data da Necessidade menor que a data de Hoje'
      #define STR0078 'Fornecedor n„o preenchido'
      #define STR0079 "Fornecedor n„o cadastrado"
      #define STR0080 'C¢digo n∆o se refere a Fornecedor'
      #define STR0081 'Fornecedor j† cadastrado p/ a Cotaá∆o deste Produto'
      #define STR0082 "Fabricante n„o cadastrado"
      #define STR0083 'C¢digo n∆o se refere a Fabricante'
      #define STR0084 'Origem n„o preenchida'
      #define STR0085 'Origem n„o cadastrada para esta Via e Destino'
      #define STR0086 'FOB Unit†rio n∆o preenchido'
      #define STR0087 'Valor de Frete n∆o deve ser preenchido ( Pre-Paid )'
      #define STR0088 'Frete n∆o preenchido'
      #define STR0089 'CondiÁ„o de Pagamento n„o preenchida'
      #define STR0090 'CondiÁ„o de Pagamento n„o Cadastrada'
      #define STR0091 'Moeda do Fob n„o preenchida'
      #define STR0092 'Moeda do Fob sem taxa de convers„o'
      #define STR0093 'C¢digo n∆o preenchido'
      #define STR0094 'C¢digo n∆o cadastrado'
      #define STR0095 'Fornecedor n∆o cadastrado nesta Concorrància'
      #define STR0096 'FOB Unit†rio n∆o pode ser negativo'
      #define STR0097 "Unidade Requisitante n„o cadastrada"
      #define STR0098 "U.R. n„o pertence a essa CotaÁ„o"
      #define STR0099 "S.I. n„o pertence a essa CotaÁ„o"
      #define STR0100 "Unidade Requisitante n∆o pertence a essa Concorrància"
      #define STR0101 "S.I. n∆o pertence a essa Concorrància"
      #define STR0102 "Calculadora"
      #define STR0103 "Help de Programa"
      #define STR0104 "Impress∆o"
      #define STR0105 "Inclus„o"
      #define STR0106 "AlteraÁ„o"
      #define STR0107 "Exclus„o"
      #define STR0108 "Itens\Forn."
      #define STR0109 "Cancelar - <Ctrl-X>"
      #define STR0110 "Avaliaá∆o do Quadro de Concorrància"
      #define STR0111 "Cod. Prod."
      #define STR0112 "Class"
      #define STR0113 "FOB Unitario"
      #define STR0114 "Vl. C.I.F."
      #define STR0115 "% Var"
      #define STR0116 "Cond Pagto"
      #define STR0117 "Processando Itens da CotaÁ„o"
      #define STR0118 "1 - Por Valor CIF"
      #define STR0119 "2 - Por Valor FOB Total"
      #define STR0120 "3 - Por Data de Entrega"
      #define STR0121 "Seleá∆o da Avaliaá∆o"
      #define STR0122 "Unidade Requ."
      #define STR0123 "S.I. Nß"
      #define STR0124 "Tipo de Apuraá∆o"
      #define STR0125 "Consulta U.R. da Cotaá∆o: "
      #define STR0126 "Consulta S.I. da Cotaá∆o: "
      #define STR0127 "Processando Item No: "
      #define STR0128 "Classificando Item No: "
      #define STR0129 "Itens do Fornecedor..."
      #define STR0130 "C¢digo do Fornecedor "
      #define STR0131 "Itens do Fornecedor: "
      #define STR0132 "Alterar FOB Unit†rio"
      #define STR0133 "Grava"
      #define STR0134 "Sair"
      #define STR0135 "FOB Unit†rio do Item: "
      #define STR0136 "Novo"
      #define STR0137 "Atual"
      #define STR0138 "FOB Unit†rio"
   #ENDIF
#ENDIF
