#IFDEF SPANISH
   #define STR0001 "Imprimiendo ..."
   #define STR0002 "Aprobado p/Envio"
   #define STR0003 "Envio al SISCOMEX / SUFRAMA"
   #define STR0004 "Nombre del Archivo"
   #define STR0005 "N.C.M."
   #define STR0006 "Fabricante"
   #define STR0007 "NALADI"
   #define STR0008 "ALADI"
   #define STR0009 "No fue posible abrir el archivo de trabajo"
   #define STR0010 "Informacion"
   #define STR0011 "Extraccion de Datos para el Siscomex / Suframa"
   #define STR0012 "Seleccionando registros de la PLI ..."
   #define STR0013 "­No hay registros para esta seleccion!"
   #define STR0014 "Marca/Des"
   #define STR0015 "Todos"
   #define STR0016 "Envio"
   #define STR0017 "Informe"
   #define STR0018 "NUMERO DE LI EN EASY NO ARCHIVADO"
   #define STR0019 "NUMERO DE LI EN EASY YA ENVIADO Y APROBADO "
   #define STR0020 "NUMERO DE LI EN EASY YA ENVIADO Y NO APROBADO"
   #define STR0021 "NUMERO DE LI EN EASY NO ARCHIVADO "
   #define STR0022 "Fecha final es menor que la fecha inicial"
   #define STR0023 "­No hay registros marcados para el envio!"
   #define STR0024 '¨Confirma envio de registros?'
   #define STR0025 'Generando Archivo Para Suframa'
   #define STR0026 'Atencion, el nombre del archivo generado es "'
   #define STR0027 'Procesando Registro Nro. '
   #define STR0028 "DISTRICTO INDUSTRIAL"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Imprimindo ..."
      #define STR0002 "LIberado p/Envio"
      #define STR0003 "Envio ao SISCOMEX / SUFRAMA"
      #define STR0004 "Nome do Arquivo"
      #define STR0005 "N.C.M."
      #define STR0006 "Fabricante"
      #define STR0007 "NALADI"
      #define STR0008 "ALADI"
      #define STR0009 "Não foi possível abrir o arquivo de trabalho"
      #define STR0010 "Informação"
      #define STR0011 "Extração de Dados para o Siscomex / Suframa"
      #define STR0012 "Selecionando registros da PLI ..."
      #define STR0013 "Não existem registros para esta seleção !"
      #define STR0014 "Marca/Des"
      #define STR0015 "Todos"
      #define STR0016 "Envio"
      #define STR0017 "Relatório"
      #define STR0018 "NÚMERO DA LI NO EASY NÃO CADASTRADO"
      #define STR0019 "NÚMERO DA LI NO EASY JÁ ENVIADO E APROVADO "
      #define STR0020 "NÚMERO DA LI NO EASY JÁ ENVIADO E NÃO APROVADO"
      #define STR0021 "NÚMERO DA LI NO EASY NÃO CADASTRADO "
      #define STR0022 "Data final é menor que a data inicial"
      #define STR0023 "Não existem registros marcados para o envio !"
      #define STR0024 'Confirma o envio dos registros ?'
      #define STR0025 'Gerando Arquivo Para Suframa'
      #define STR0026 'Atenção o nome do arquivo gerado é "'
      #define STR0027 'Processando Registro Nr '
      #define STR0028 "DISTRITO INDUSTRIAL"
   #ELSE
      #define STR0001 "Imprimindo ..."
      #define STR0002 "LIberado p/Envio"
      #define STR0003 "Envio ao SISCOMEX / SUFRAMA"
      #define STR0004 "Nome do Arquivo"
      #define STR0005 "N.C.M."
      #define STR0006 "Fabricante"
      #define STR0007 "NALADI"
      #define STR0008 "ALADI"
      #define STR0009 "Não foi possível abrir o arquivo de trabalho"
      #define STR0010 "Informação"
      #define STR0011 "Extração de Dados para o Siscomex / Suframa"
      #define STR0012 "Selecionando registros da PLI ..."
      #define STR0013 "Não existem registros para esta seleção !"
      #define STR0014 "Marca/Des"
      #define STR0015 "Todos"
      #define STR0016 "Envio"
      #define STR0017 "Relatório"
      #define STR0018 "NÚMERO DA LI NO EASY NÃO CADASTRADO"
      #define STR0019 "NÚMERO DA LI NO EASY JÁ ENVIADO E APROVADO "
      #define STR0020 "NÚMERO DA LI NO EASY JÁ ENVIADO E NÃO APROVADO"
      #define STR0021 "NÚMERO DA LI NO EASY NÃO CADASTRADO "
      #define STR0022 "Data final é menor que a data inicial"
      #define STR0023 "Não existem registros marcados para o envio !"
      #define STR0024 'Confirma o envio dos registros ?'
      #define STR0025 'Gerando Arquivo Para Suframa'
      #define STR0026 'Atenção o nome do arquivo gerado é "'
      #define STR0027 'Processando Registro Nr '
      #define STR0028 "DISTRITO INDUSTRIAL"
   #ENDIF
#ENDIF
