#IFDEF SPANISH
   #define STR0001 "DESEMBOLSO REALIZADO"
   #define STR0002 "EN PROCESAMIENTO - ESPERE..."
   #define STR0003 "BUSCANDO DATOS - ESPERE..."
   #define STR0004 "Buscando Proceso: "
   #define STR0005 "Fecha"
   #define STR0006 "Gasto"
   #define STR0007 "Nro.P.O."
   #define STR0008 "Valor"
   #define STR0009 "Proveedor"
   #define STR0010 "Genera Archivo"
   #define STR0011 "Informe"
   #define STR0012 "Procesando Archivo Temporal..."
   #define STR0013 "IMPORTADOR NO ENCONTRADO"
   #define STR0014 "Informacion"
   #define STR0015 "Analitico"
   #define STR0016 "Sintetico"
   #define STR0017 "Valor $"
   #define STR0018 "P.O. NO ARCHIVADO"
   #define STR0019 "P.O. PERTENECE A OTRO IMPORTADOR"
   #define STR0020 ', todos los P.O.s'
   #define STR0021 ', P.O. Nro. '
   #define STR0022 "GASTO NO ARCHIVADO"
   #define STR0023 "GASTO NO PUEDE SER VALOR C.I.F."
   #define STR0024 ', todas los gastos'
   #define STR0025 ', gasto '
   #define STR0026 "Computando Gastos"
   #define STR0027 "NO HAY REGISTROS PARA CONSULTA"
   #define STR0028 "Importador :"
   #define STR0029 "Total :"
   #define STR0030 'FECHA INICIAL MAYOR QUE FECHA FINAL'
   #define STR0031 ' - en el periodo de '
   #define STR0032 " a "
   #define STR0033 "Impresion del Informe de Desembolso Realizado"
   #define STR0034 "Analitico - Por P.O. ( "
   #define STR0035 'Todos'
   #define STR0036 "TOTAL DEL DIA....................:"
   #define STR0037 "TOTAL DEL P.O....................:"
   #define STR0038 "Analitico - Por Gasto ( "
   #define STR0039 'Todas'
   #define STR0040 "TOTAL DEL DIA.............:"
   #define STR0041 "TOTAL DEL GASTO...........:"
   #define STR0042 "ANULADO POR EL OPERADOR"
   #define STR0043 "TOTAL GENERAL....................:"
   #define STR0044 "TOTAL GENERAL.............:"
   #define STR0045 "Importador.: "
   #define STR0046 "General"
   #define STR0047 'Nro.P.O.'
   #define STR0048 'Fecha'
   #define STR0049 'Proceso'
   #define STR0050 'Gasto'
   #define STR0051 '          Valor $'
   #define STR0052 'Proveedor'
   #define STR0053 'Gasto                                  Fecha                                    Valor $     Proveedor'
   #define STR0054 " con "
   #define STR0055 " CONTADO"
   #define STR0056 "NTECIPADO A"
   #define STR0057 " - Clasificacion"
   #define STR0058 "Tipo"
   #define STR0059 "Tipo no archivado"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "DESEMBOLSO REALIZADO"
      #define STR0002 "EM PROCESSAMENTO - AGUARDE..."
      #define STR0003 "PESQUISANDO DADOS - AGUARDE..."
      #define STR0004 "Pesquisando Processo: "
      #define STR0005 "Data"
      #define STR0006 "Despesa"
      #define STR0007 "No. P.O."
      #define STR0008 "Valor"
      #define STR0009 "Fornecedor"
      #define STR0010 "Gera Arquivo"
      #define STR0011 "Relatorio"
      #define STR0012 "Processando Arquivo Temporario..."
      #define STR0013 "IMPORTADOR NÇO ENCONTRADO"
      #define STR0014 "Informação"
      #define STR0015 "Analitico"
      #define STR0016 "Sintetico"
      #define STR0017 "Valor R$"
      #define STR0018 "P.O. NÇO CADASTRADO"
      #define STR0019 "P.O. PERTENCE A OUTRO IMPORTADOR"
      #define STR0020 ', todos os P.O.s'
      #define STR0021 ', P.O. No. '
      #define STR0022 "DESPESA NÇO CADASTRADA"
      #define STR0023 "DESPESA NÇO PODE SER VALOR C.I.F."
      #define STR0024 ', todas as despesas'
      #define STR0025 ', despesa '
      #define STR0026 "Apurando Despesas"
      #define STR0027 "NÇO EXISTEM REGISTROS PARA CONSULTA"
      #define STR0028 "Importador :"
      #define STR0029 "Total :"
      #define STR0030 'DATA INICIAL MAIOR QUE DATA FINAL'
      #define STR0031 ' - no periodo de '
      #define STR0032 " ate "
      #define STR0033 "Impressao do Relatorio de Desembolso Realizado"
      #define STR0034 "Analitico - Por P.O. ( "
      #define STR0035 'Todos'
      #define STR0036 "TOTAL DO DIA.....................:"
      #define STR0037 "TOTAL DO P.O.....................:"
      #define STR0038 "Analitico - Por Despesa ( "
      #define STR0039 'Todas'
      #define STR0040 "TOTAL DO DIA..............:"
      #define STR0041 "TOTAL DA DESPESA..........:"
      #define STR0042 "CANCELADO PELO OPERADOR"
      #define STR0043 "TOTAL GERAL......................:"
      #define STR0044 "TOTAL GERAL...............:"
      #define STR0045 "Importador.: "
      #define STR0046 "Geral"
      #define STR0047 'No. P.O.'
      #define STR0048 'Data'
      #define STR0049 'Processo'
      #define STR0050 'Despesa'
      #define STR0051 '          Valor R$'
      #define STR0052 'Fornecedor'
      #define STR0053 'Despesa                                Data                                     Valor R$    Fornecedor'
      #define STR0054 " com "
      #define STR0055 " VISTA"
      #define STR0056 "NTECIPADO A"
      #define STR0057 " - Classificacao"
      #define STR0058 "Tipo"
      #define STR0059 "Tipo nÆo cadastrado"
   #ELSE
      #define STR0001 "DESEMBOLSO REALIZADO"
      #define STR0002 "EM PROCESSAMENTO - AGUARDE..."
      #define STR0003 "PESQUISANDO DADOS - AGUARDE..."
      #define STR0004 "Pesquisando Processo: "
      #define STR0005 "Data"
      #define STR0006 "Despesa"
      #define STR0007 "No. P.O."
      #define STR0008 "Valor"
      #define STR0009 "Fornecedor"
      #define STR0010 "Gera Arquivo"
      #define STR0011 "Relatorio"
      #define STR0012 "Processando Arquivo Temporario..."
      #define STR0013 "IMPORTADOR NÇO ENCONTRADO"
      #define STR0014 "Informação"
      #define STR0015 "Analitico"
      #define STR0016 "Sintetico"
      #define STR0017 "Valor R$"
      #define STR0018 "P.O. NÇO CADASTRADO"
      #define STR0019 "P.O. PERTENCE A OUTRO IMPORTADOR"
      #define STR0020 ', todos os P.O.s'
      #define STR0021 ', P.O. No. '
      #define STR0022 "DESPESA NÇO CADASTRADA"
      #define STR0023 "DESPESA NÇO PODE SER VALOR C.I.F."
      #define STR0024 ', todas as despesas'
      #define STR0025 ', despesa '
      #define STR0026 "Apurando Despesas"
      #define STR0027 "NÇO EXISTEM REGISTROS PARA CONSULTA"
      #define STR0028 "Importador :"
      #define STR0029 "Total :"
      #define STR0030 'DATA INICIAL MAIOR QUE DATA FINAL'
      #define STR0031 ' - no periodo de '
      #define STR0032 " ate "
      #define STR0033 "Impressao do Relatorio de Desembolso Realizado"
      #define STR0034 "Analitico - Por P.O. ( "
      #define STR0035 'Todos'
      #define STR0036 "TOTAL DO DIA.....................:"
      #define STR0037 "TOTAL DO P.O.....................:"
      #define STR0038 "Analitico - Por Despesa ( "
      #define STR0039 'Todas'
      #define STR0040 "TOTAL DO DIA..............:"
      #define STR0041 "TOTAL DA DESPESA..........:"
      #define STR0042 "CANCELADO PELO OPERADOR"
      #define STR0043 "TOTAL GERAL......................:"
      #define STR0044 "TOTAL GERAL...............:"
      #define STR0045 "Importador.: "
      #define STR0046 "Geral"
      #define STR0047 'No. P.O.'
      #define STR0048 'Data'
      #define STR0049 'Processo'
      #define STR0050 'Despesa'
      #define STR0051 '          Valor R$'
      #define STR0052 'Fornecedor'
      #define STR0053 'Despesa                                Data                                     Valor R$    Fornecedor'
      #define STR0054 " com "
      #define STR0055 " VISTA"
      #define STR0056 "NTECIPADO A"
      #define STR0057 " - Classificacao"
      #define STR0058 "Tipo"
      #define STR0059 "Tipo nÆo cadastrado"
   #ENDIF
#ENDIF
