#IFDEF SPANISH
   #define STR0001 "BUSCANDO DATOS - ESPERE..."
   #define STR0002 "Fecha"
   #define STR0003 "Gasto"
   #define STR0004 "Nro.P.O."
   #define STR0005 "Valor"
   #define STR0006 "Proveedor"
   #define STR0007 "Tabla"
   #define STR0008 "Prevision de Desembolso en U$S"
   #define STR0009 "GENERAL"
   #define STR0010 "Analitico"
   #define STR0011 "Sintetico"
   #define STR0012 "Proceso"
   #define STR0013 ', todos los Procesos'
   #define STR0014 ', Proceso '
   #define STR0015 ', todos los P.O.s'
   #define STR0016 ', P.O. Nro. '
   #define STR0017 ', todas los gastos'
   #define STR0018 ', gasto '
   #define STR0019 "Orden Por Fecha solamente para Informe Anal°tico"
   #define STR0020 "Atencion"
   #define STR0021 ", Periodo de "
   #define STR0022 " a "
   #define STR0023 ', en el periodo de '
   #define STR0024 ' hasta '
   #define STR0025 "Mes"
   #define STR0026 "Buscando procesos"
   #define STR0027 "No hay registros a ser listados"
   #define STR0028 "Informaciones"
   #define STR0029 "Importador"
   #define STR0030 "Total General "
   #define STR0031 "No fue posible la apertura del Archivo de Trabajo"
   #define STR0032 "Procesando P.O. Nro. "
   #define STR0033 "Procesando P.L.I. ref. P.O. Nro. "
   #define STR0034 "Proceso referente a P.O.: "
   #define STR0035 "01,P,PROVEED.EXTRANJERO  ,IMPORTACION EN MARCHA         ,"
   #define STR0036 "TXT SOLO PUEDE SER GENERADO P/EL ANALITICO"
   #define STR0037 "Informacion"
   #define STR0038 "ARCHIVO "
   #define STR0039 "®YA EXISTE, SUPERPONER?"
   #define STR0040 "Superponer"
   #define STR0041 "ERROR EN CREACION DEL "
   #define STR0042 " CODIGO = "
   #define STR0043 "NO HAY REGISTROS A SER GENERADOS"
   #define STR0044 " GENERADO CON EXITO"
   #define STR0045 "Impresion del Informe de Prevision de Desembolso"
   #define STR0046 "Prevision de Desembolso"
   #define STR0047 "A Rayas"
   #define STR0048 "Importacion"
   #define STR0049 "Procesando Registros..."
   #define STR0050 "Analitico - Por Proceso ( "
   #define STR0051 'Todos'
   #define STR0052 "TOTAL DEL DIA..................:"
   #define STR0053 "TOTAL DEL PROCESO..............:"
   #define STR0054 "Analitico - Por P.O. ( "
   #define STR0055 "TOTAL DE P.O...................:"
   #define STR0056 "Analitico - Por Gasto   ( "
   #define STR0057 'Todas'
   #define STR0058 "TOTAL DEL DIA.............:"
   #define STR0059 "TOTAL DEL GASTO...........:"
   #define STR0060 "Analitico - Por Fecha (Periodo de "
   #define STR0061 "TOTAL DEL GASTO.......:"
   #define STR0062 "TOTAL DEL DIA.........:"
   #define STR0063 "ANULADO POR EL OPERADOR"
   #define STR0064 "TOTAL GENERAL..................:"
   #define STR0065 "TOTAL GENERAL.............:"
   #define STR0066 "Importador.: "
   #define STR0067 'Nro.Proceso        Fecha       Gasto                                                 Valor  Proveedor          Tabla     Embarque    Condicion     Pago'
   #define STR0068 'Nro.P.O.           Fecha       Gasto                                                 Valor  Proveedor          Tabla     Embarque    Condicion     Pago'
   #define STR0069 'Gasto                                  Fecha      Nro.P.O.                           Valor  Tabla     Proveedor          Embarque    Condicion     Pago'
   #define STR0070 'Fecha       Gasto                                 Nro.P.O.                           Valor  Tabla     Proveedor          Embarque    Condicion     Pago'
   #define STR0071 "Sintetico por Proceso  ( "
   #define STR0072 "Sintetico por P.O. ( "
   #define STR0073 "Sintetico por Gasto   ( "
   #define STR0074 'TOTAL GENERAL.......:'
   #define STR0075 'Nro.Proceso  / Proveedor '
   #define STR0076 'Nro.P.O. / Proveedor '
   #define STR0077 'Gasto  '
   #define STR0078 'Enero'
   #define STR0079 'Febrero'
   #define STR0080 'Marzo'
   #define STR0081 'Abril'
   #define STR0082 'Mayo'
   #define STR0083 'Junio'
   #define STR0084 'Julio'
   #define STR0085 'Agosto'
   #define STR0086 'Septiembre'
   #define STR0087 'Octubre'
   #define STR0088 'Noviembre'
   #define STR0089 'Diciembre'
   #define STR0090 ' de '
   #define STR0091 "RESUMEN DE PREVISION EN DOLAR"
   #define STR0092 " DIAS"
   #define STR0093 " coN "
   #define STR0094 " CONTADO"
   #define STR0095 "ANTICIPADO A"
   #define STR0096 "P.O. no archivado"
   #define STR0097 "Proceso no archivado"
   #define STR0098 "Gasto no archivado"
   #define STR0099 "Gasto no puede ser valor C.I.F."
   #define STR0100 "Mes fuera del periodo de '01' A '12'"
   #define STR0101 "A§o no informado"
   #define STR0102 "Fecha Final menor que Fecha Inicial"
   #define STR0103 "Carrgando la Tabla de Precalculo Nro. "
   #define STR0104 " - Espere..."
   #define STR0105 "Pagina..:"
   #define STR0106 "Average Tecnologia"
   #define STR0107 "Emision.:"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "PESQUISANDO DADOS - AGUARDE..."
      #define STR0002 "Data"
      #define STR0003 "Despesa"
      #define STR0004 "No. P.O."
      #define STR0005 "Valor"
      #define STR0006 "Fornecedor"
      #define STR0007 "Tabela"
      #define STR0008 "Previsao de Desembolso em US$"
      #define STR0009 "GERAL"
      #define STR0010 "Analitico"
      #define STR0011 "Sintetico"
      #define STR0012 "Processo"
      #define STR0013 ', todos os Processos'
      #define STR0014 ', Processo '
      #define STR0015 ', todos os P.O.s'
      #define STR0016 ', P.O. No. '
      #define STR0017 ', todas as despesas'
      #define STR0018 ', despesa '
      #define STR0019 "Ordem Por Data somente para Relat¢rio Anal°tico"
      #define STR0020 "Atená∆o"
      #define STR0021 ", Periodo de "
      #define STR0022 " a "
      #define STR0023 ', no periodo de '
      #define STR0024 ' ate '
      #define STR0025 "Mes"
      #define STR0026 "Pesquisando processos"
      #define STR0027 "N†o h† registros a serem listados"
      #define STR0028 "Informaá‰es"
      #define STR0029 "Importador"
      #define STR0030 "Total Geral "
      #define STR0031 "N∆o foi poss°vel a abertura do Arquivo de Trabalho"
      #define STR0032 "Processando P.O. No. "
      #define STR0033 "Processando P.L.I. ref. P.O. No. "
      #define STR0034 "Processo referente a P.O.: "
      #define STR0035 "01,P,FORNEC.ESTRANGEIRO  ,IMPORTACAO EM ANDAMENTO       ,"
      #define STR0036 "TXT SOMENTE PODE SER GERADO P/ O ANALITICO"
      #define STR0037 "Informaá∆o"
      #define STR0038 "ARQUIVO "
      #define STR0039 " Jµ EXISTE, SOBREPOR ?"
      #define STR0040 "Sobrepor"
      #define STR0041 "ERRO NA CRIAÄ«O DO "
      #define STR0042 " CODIGO = "
      #define STR0043 "N«O Hµ  REGISTROS A SEREM GERADOS"
      #define STR0044 " GERADO COM SUCESSO"
      #define STR0045 "Impressao do Relatorio da Previsao de Desembolso"
      #define STR0046 "Previsao de Desembolso"
      #define STR0047 "Zebrado"
      #define STR0048 "Importaáao"
      #define STR0049 "Processando Registros..."
      #define STR0050 "Analitico - Por Processo ( "
      #define STR0051 'Todos'
      #define STR0052 "TOTAL DO DIA...................:"
      #define STR0053 "TOTAL DO PROCESSO..............:"
      #define STR0054 "Analitico - Por P.O. ( "
      #define STR0055 "TOTAL DO P.O...................:"
      #define STR0056 "Analitico - Por Despesa ( "
      #define STR0057 'Todas'
      #define STR0058 "TOTAL DO DIA..............:"
      #define STR0059 "TOTAL DA DESPESA..........:"
      #define STR0060 "Analitico - Por Data ( Periodo de "
      #define STR0061 "TOTAL DO DESPESA......:"
      #define STR0062 "TOTAL DA DIA..........:"
      #define STR0063 "CANCELADO PELO OPERADOR"
      #define STR0064 "TOTAL GERAL....................:"
      #define STR0065 "TOTAL GERAL...............:"
      #define STR0066 "Importador.: "
      #define STR0067 'No. Processo       Data        Despesa                                               Valor  Fornecedor         Tabela    Embarque    Condicao Pagamento'
      #define STR0068 'No. P.O.           Data        Despesa                                               Valor  Fornecedor         Tabela    Embarque    Condicao Pagamento'
      #define STR0069 'Despesa                                Data        No P.O.                           Valor  Tabela    Fornecedor         Embarque    Condicao Pagamento'
      #define STR0070 'Data        Despesa                                No P.O.                           Valor  Tabela    Fornecedor         Embarque    Condicao Pagamento'
      #define STR0071 "Sintetico por Processo ( "
      #define STR0072 "Sintetico por P.O. ( "
      #define STR0073 "Sintetico por Despesa ( "
      #define STR0074 'TOTAL GERAL.........:'
      #define STR0075 'No. Processo / Fornecedor'
      #define STR0076 'No. P.O. / Fornecedor'
      #define STR0077 'Despesa'
      #define STR0078 'Janeiro'
      #define STR0079 'Fevereiro'
      #define STR0080 'Marco'
      #define STR0081 'Abril'
      #define STR0082 'Maio'
      #define STR0083 'Junho'
      #define STR0084 'Julho'
      #define STR0085 'Agosto'
      #define STR0086 'Setembro'
      #define STR0087 'Outubro'
      #define STR0088 'Novembro'
      #define STR0089 'Dezembro'
      #define STR0090 ' de '
      #define STR0091 "RESUMO DA PREVISAO EM DOLAR"
      #define STR0092 " DIAS"
      #define STR0093 " com "
      #define STR0094 " VISTA"
      #define STR0095 "ANTECIPADO A"
      #define STR0096 "P.O. n∆o cadastrado"
      #define STR0097 "Processo n∆o cadastrado"
      #define STR0098 "Despesa n∆o cadastrada"
      #define STR0099 "Despesa n∆o pode ser valor C.I.F."
      #define STR0100 "Màs fora do periodo de '01' A '12'"
      #define STR0101 "Ano n∆o informado"
      #define STR0102 "Data Final menor que e Data Inicial"
      #define STR0103 "Carregando a Tabela de Pre-Calculo No. "
      #define STR0104 " - Aguarde..."
      #define STR0105 "Pagina..:"
      #define STR0106 "Average Tecnologia"
      #define STR0107 "Emissao.:"
   #ELSE
      #define STR0001 "PESQUISANDO DADOS - AGUARDE..."
      #define STR0002 "Data"
      #define STR0003 "Despesa"
      #define STR0004 "No. P.O."
      #define STR0005 "Valor"
      #define STR0006 "Fornecedor"
      #define STR0007 "Tabela"
      #define STR0008 "Previsao de Desembolso em US$"
      #define STR0009 "GERAL"
      #define STR0010 "Analitico"
      #define STR0011 "Sintetico"
      #define STR0012 "Processo"
      #define STR0013 ', todos os Processos'
      #define STR0014 ', Processo '
      #define STR0015 ', todos os P.O.s'
      #define STR0016 ', P.O. No. '
      #define STR0017 ', todas as despesas'
      #define STR0018 ', despesa '
      #define STR0019 "Ordem Por Data somente para Relat¢rio Anal°tico"
      #define STR0020 "Atená∆o"
      #define STR0021 ", Periodo de "
      #define STR0022 " a "
      #define STR0023 ', no periodo de '
      #define STR0024 ' ate '
      #define STR0025 "Mes"
      #define STR0026 "Pesquisando processos"
      #define STR0027 "N†o h† registros a serem listados"
      #define STR0028 "Informaá‰es"
      #define STR0029 "Importador"
      #define STR0030 "Total Geral "
      #define STR0031 "N∆o foi poss°vel a abertura do Arquivo de Trabalho"
      #define STR0032 "Processando P.O. No. "
      #define STR0033 "Processando P.L.I. ref. P.O. No. "
      #define STR0034 "Processo referente a P.O.: "
      #define STR0035 "01,P,FORNEC.ESTRANGEIRO  ,IMPORTACAO EM ANDAMENTO       ,"
      #define STR0036 "TXT SOMENTE PODE SER GERADO P/ O ANALITICO"
      #define STR0037 "Informaá∆o"
      #define STR0038 "ARQUIVO "
      #define STR0039 " Jµ EXISTE, SOBREPOR ?"
      #define STR0040 "Sobrepor"
      #define STR0041 "ERRO NA CRIAÄ«O DO "
      #define STR0042 " CODIGO = "
      #define STR0043 "N«O Hµ  REGISTROS A SEREM GERADOS"
      #define STR0044 " GERADO COM SUCESSO"
      #define STR0045 "Impressao do Relatorio da Previsao de Desembolso"
      #define STR0046 "Previsao de Desembolso"
      #define STR0047 "Zebrado"
      #define STR0048 "Importaáao"
      #define STR0049 "Processando Registros..."
      #define STR0050 "Analitico - Por Processo ( "
      #define STR0051 'Todos'
      #define STR0052 "TOTAL DO DIA...................:"
      #define STR0053 "TOTAL DO PROCESSO..............:"
      #define STR0054 "Analitico - Por P.O. ( "
      #define STR0055 "TOTAL DO P.O...................:"
      #define STR0056 "Analitico - Por Despesa ( "
      #define STR0057 'Todas'
      #define STR0058 "TOTAL DO DIA..............:"
      #define STR0059 "TOTAL DA DESPESA..........:"
      #define STR0060 "Analitico - Por Data ( Periodo de "
      #define STR0061 "TOTAL DO DESPESA......:"
      #define STR0062 "TOTAL DA DIA..........:"
      #define STR0063 "CANCELADO PELO OPERADOR"
      #define STR0064 "TOTAL GERAL....................:"
      #define STR0065 "TOTAL GERAL...............:"
      #define STR0066 "Importador.: "
      #define STR0067 'No. Processo       Data        Despesa                                               Valor  Fornecedor         Tabela    Embarque    Condicao Pagamento'
      #define STR0068 'No. P.O.           Data        Despesa                                               Valor  Fornecedor         Tabela    Embarque    Condicao Pagamento'
      #define STR0069 'Despesa                                Data        No P.O.                           Valor  Tabela    Fornecedor         Embarque    Condicao Pagamento'
      #define STR0070 'Data        Despesa                                No P.O.                           Valor  Tabela    Fornecedor         Embarque    Condicao Pagamento'
      #define STR0071 "Sintetico por Processo ( "
      #define STR0072 "Sintetico por P.O. ( "
      #define STR0073 "Sintetico por Despesa ( "
      #define STR0074 'TOTAL GERAL.........:'
      #define STR0075 'No. Processo / Fornecedor'
      #define STR0076 'No. P.O. / Fornecedor'
      #define STR0077 'Despesa'
      #define STR0078 'Janeiro'
      #define STR0079 'Fevereiro'
      #define STR0080 'Marco'
      #define STR0081 'Abril'
      #define STR0082 'Maio'
      #define STR0083 'Junho'
      #define STR0084 'Julho'
      #define STR0085 'Agosto'
      #define STR0086 'Setembro'
      #define STR0087 'Outubro'
      #define STR0088 'Novembro'
      #define STR0089 'Dezembro'
      #define STR0090 ' de '
      #define STR0091 "RESUMO DA PREVISAO EM DOLAR"
      #define STR0092 " DIAS"
      #define STR0093 " com "
      #define STR0094 " VISTA"
      #define STR0095 "ANTECIPADO A"
      #define STR0096 "P.O. n∆o cadastrado"
      #define STR0097 "Processo n∆o cadastrado"
      #define STR0098 "Despesa n∆o cadastrada"
      #define STR0099 "Despesa n∆o pode ser valor C.I.F."
      #define STR0100 "Màs fora do periodo de '01' A '12'"
      #define STR0101 "Ano n∆o informado"
      #define STR0102 "Data Final menor que e Data Inicial"
      #define STR0103 "Carregando a Tabela de Pre-Calculo No. "
      #define STR0104 " - Aguarde..."
      #define STR0105 "Pagina..:"
      #define STR0106 "Average Tecnologia"
      #define STR0107 "Emissao.:"
   #ENDIF
#ENDIF
