#IFDEF SPANISH
         #define STR0001  "N§ S.I."
         #define STR0002  "Fc. S.I."
         #define STR0003  "Item"
         #define STR0004  "Descripcion"
         #define STR0005  "Proveedor"
         #define STR0006  "Prevision Entrega"
         #define STR0007  "Entrega"
         #define STR0008  "Plazo Solicitado"
         #define STR0009  "Plazo Previsto"
         #define STR0010  "Plazo Realizado"
         #define STR0011  "Work"
         #define STR0012  "Este informe exhibir  una estad¡stica sobre"
         #define STR0013  "las S.I.s atendidas despu‚s del plazo solicitado."
         #define STR0014  "S.I.s fuera de Lead Time"
         #define STR0015  "EICTR320"
         #define STR0016  "S.I.s fuera del Lead Time"
         #define STR0017  "Buscando Entregas..."
         #define STR0018  'ITEM '
         #define STR0019  ' NO ARCHIVADO P/ O '
         #define STR0020  "Informacion"

#ELSE
   #IFDEF ENGLISH
         #define STR0001  "N§ S.I."
         #define STR0002  "Dt. S.I."
         #define STR0003  "Item"
         #define STR0004  "Descri‡ao"
         #define STR0005  "Fornecedor"
         #define STR0006  "Previsao Entrega"
         #define STR0007  "Entrega"
         #define STR0008  "Prazo Solicitado"
         #define STR0009  "Prazo Previsto"
         #define STR0010  "Prazo Realizado"
         #define STR0011  "Work"
         #define STR0012  "Este relatorio ir  exibir um estat¡stica sobre"
         #define STR0013  "as S.I.s atendidas acima do prazo solicitado."
         #define STR0014  "S.I.s fora de Lead Time"
         #define STR0015  "EICTR320"
         #define STR0016  "S.I.s fora do Lead Time"
         #define STR0017  "Pesquisando Entregas..."
         #define STR0018  'ITEM '
         #define STR0019  ' NÇO CADASTRADO P/ O '
         #define STR0020  "Informação"

   #ELSE
         #define STR0001  "N§ S.I."
         #define STR0002  "Dt. S.I."
         #define STR0003  "Item"
         #define STR0004  "Descri‡ao"
         #define STR0005  "Fornecedor"
         #define STR0006  "Previsao Entrega"
         #define STR0007  "Entrega"
         #define STR0008  "Prazo Solicitado"
         #define STR0009  "Prazo Previsto"
         #define STR0010  "Prazo Realizado"
         #define STR0011  "Work"
         #define STR0012  "Este relatorio ir  exibir um estat¡stica sobre"
         #define STR0013  "as S.I.s atendidas acima do prazo solicitado."
         #define STR0014  "S.I.s fora de Lead Time"
         #define STR0015  "EICTR320"
         #define STR0016  "S.I.s fora do Lead Time"
         #define STR0017  "Pesquisando Entregas..."
         #define STR0018  'ITEM '
         #define STR0019  ' NÇO CADASTRADO P/ O '
         #define STR0020  "Informação"
   #ENDIF
#ENDIF
