#IFDEF SPANISH
       #define STR0001  "ANULADO POR EL OPERADOR"
       #define STR0002  "Plazo Promedio.: "
       #define STR0003  " Dias"
       #define STR0004  "Seleccion de Importador"
       #define STR0005  "Codigo del Importador no encontrado"
       #define STR0006  "Informacion"
       #define STR0007  "Registro seleccionado es del tipo consignatario"
       #define STR0008  "Codigo"
       #define STR0009  "Informe el Codigo del Importador o presione F3"
       #define STR0010  "General"
       #define STR0011  "Import "
       #define STR0012  "Lead Time"
       #define STR0013  "Plazo Promedio"
       #define STR0014  "No Inf."
       #define STR0015  "COMPRADOR NO ARCHIVADO"
       #define STR0016  "DEPOSITO DE ENTREGA NO ARCHIVADO"
       #define STR0017  "Calculadora"
       #define STR0018  "Agenda"
       #define STR0019  "Administrador de Impresion"
       #define STR0020  "Help de Programa"
       #define STR0021  "Primero"
       #define STR0022  "Proximo"
       #define STR0023  "Anterior"
       #define STR0024  "Ultimo"
       #define STR0025  "Anular"
       #define STR0026  "Con Cobertura hasta 180 dias       "
       #define STR0027  "Con Cobertura de 181 hasta 360 dias"
       #define STR0028  "Con Cobertura despues de 360 dias  "
       #define STR0029  "Sin Cobertura                    "
       #define STR0030  "FECHA FINAL MENOR QUE FECHA INICIAL"
       #define STR0031  "No hay area disponible para apertura del Archivo de Work"
       #define STR0032  "Orden"
       #define STR0033  "Observacion"
       #define STR0034  "Orden de Mensajes"
       #define STR0047  'Enero'
       #define STR0048  'Febrero'
       #define STR0049  'Marzo'
       #define STR0050  'Abril'
       #define STR0051  'Mayo'
       #define STR0052  'Junio'
       #define STR0053  'Julio'
       #define STR0054  'Agosto'
       #define STR0055  'Septiembre'
       #define STR0056  'Octubre'
       #define STR0057  'Noviembre'
       #define STR0058  'Diciembre'
	   #define STR0059  "Data/Date"        
	   #define STR0060  "Fax"              
       #define STR0061  "Pages (including" 
	   #define STR0062  "De/From"              
       #define STR0063  "Departamento/Division"
	   #define STR0064  "Nome/Name"            
       #define STR0065  "Para/To"  
	   #define STR0066  "Assunto/Subject: "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "CANCELADO PELO OPERADOR"
         #define STR0002  "Prazo Medio.: "
         #define STR0003  " Dias"
         #define STR0004  "Seleção de Importador"
         #define STR0005  "Código do Importador não encontrado"
         #define STR0006  "Informação"
         #define STR0007  "Registro selecionado é do tipo consignatário"
         #define STR0008  "C¢digo"
         #define STR0009  "Informe o C¢digo do Importador ou tecle F3"
         #define STR0010  "Geral"
         #define STR0011  "Import "
         #define STR0012  "Lead Time"
         #define STR0013  "Prazo M‚dio"
         #define STR0014  "Nao Inf."
         #define STR0015  "COMPRADOR NAO CADASTRADO"
         #define STR0016  "LOCAL DE ENTREGA NAO CADASTRADO"
         #define STR0017  "Calculadora"
         #define STR0018  "Agenda"
         #define STR0019  "Gerenciador de Impressao"
         #define STR0020  "Help de Programa"
         #define STR0021  "Primeiro"
         #define STR0022  "Proximo"
         #define STR0023  "Anterior"
         #define STR0024  "Ultimo"
         #define STR0025  "Cancelar"
         #define STR0026  "Com Cobertura ate 180 dias       "
         #define STR0027  "Com Cobertura de 181 ate 360 dias"
         #define STR0028  "Com Cobertura ate Acima 360 dias "
         #define STR0029  "Sem Cobertura                    "
         #define STR0030  "DATA FINAL MENOR QUE DATA INICIAL"
         #define STR0031  "N„o h   rea dispon¡vel para abertura do Cadastro de Work"
         #define STR0032  "Ordem"
         #define STR0033  "Observacao"
         #define STR0034  "Ordem de Mensagens"
         #define STR0047  'Janeiro'
         #define STR0048  'Fevereiro'
         #define STR0049  'Marco'
         #define STR0050  'Abril'
         #define STR0051  'Maio'
         #define STR0052  'Junho'
         #define STR0053  'Julho'
         #define STR0054  'Agosto'
         #define STR0055  'Setembro'
         #define STR0056  'Outubro'
         #define STR0057  'Novembro'
         #define STR0058  'Dezembro'
		 #define STR0059  "Data/Date"        
		 #define STR0060  "Fax"              
    	 #define STR0061  "Pages (including" 
		 #define STR0062  "De/From"              
    	 #define STR0063  "Departamento/Division"
		 #define STR0064  "Nome/Name"            
    	 #define STR0065  "Para/To"  
		 #define STR0066  "Assunto/Subject: "
   #ELSE
         #define STR0001  "CANCELADO PELO OPERADOR"
         #define STR0002  "Prazo Medio.: "
         #define STR0003  " Dias"
         #define STR0004  "Seleção de Importador"
         #define STR0005  "Código do Importador não encontrado"
         #define STR0006  "Informação"
         #define STR0007  "Registro selecionado é do tipo consignatário"
         #define STR0008  "C¢digo"
         #define STR0009  "Informe o C¢digo do Importador ou tecle F3"
         #define STR0010  "Geral"
         #define STR0011  "Import "
         #define STR0012  "Lead Time"
         #define STR0013  "Prazo M‚dio"
         #define STR0014  "Nao Inf."
         #define STR0015  "COMPRADOR NAO CADASTRADO"
         #define STR0016  "LOCAL DE ENTREGA NAO CADASTRADO"
         #define STR0017  "Calculadora"
         #define STR0018  "Agenda"
         #define STR0019  "Gerenciador de Impressao"
         #define STR0020  "Help de Programa"
         #define STR0021  "Primeiro"
         #define STR0022  "Proximo"
         #define STR0023  "Anterior"
         #define STR0024  "Ultimo"
         #define STR0025  "Cancelar"
         #define STR0026  "Com Cobertura ate 180 dias       "
         #define STR0027  "Com Cobertura de 181 ate 360 dias"
         #define STR0028  "Com Cobertura ate Acima 360 dias "
         #define STR0029  "Sem Cobertura                    "
         #define STR0030  "DATA FINAL MENOR QUE DATA INICIAL"
         #define STR0031  "N„o h   rea dispon¡vel para abertura do Cadastro de Work"
         #define STR0032  "Ordem"
         #define STR0033  "Observacao"
         #define STR0034  "Ordem de Mensagens"
         #define STR0047  'Janeiro'
         #define STR0048  'Fevereiro'
         #define STR0049  'Marco'
         #define STR0050  'Abril'
         #define STR0051  'Maio'
         #define STR0052  'Junho'
         #define STR0053  'Julho'
         #define STR0054  'Agosto'
         #define STR0055  'Setembro'
         #define STR0056  'Outubro'
         #define STR0057  'Novembro'
         #define STR0058  'Dezembro'
		 #define STR0059  "Data/Date"        
		 #define STR0060  "Fax"              
    	 #define STR0061  "Pages (including" 
		 #define STR0062  "De/From"              
    	 #define STR0063  "Departamento/Division"
		 #define STR0064  "Nome/Name"            
    	 #define STR0065  "Para/To"  
		 #define STR0066  "Assunto/Subject: "
   #ENDIF
#ENDIF
