#IFDEF SPANISH
      #define STR0001  "ø&Que es esto?"
      #define STR0002  "Consulta Estandar"
      #define STR0003  "F3 Disponible..."
#ELSE
	#IFDEF ENGLISH
	   #define STR0001  "&What is This?"
	   #define STR0002  "Standard Query"
      #define STR0003  "F3 Available..."
	#ELSE
	   #define STR0001  "&O que Ç isto?"
	   #define STR0002  "Consulta Padr∆o"
      #define STR0003  "F3 Dispon°vel..."
	#ENDIF
#ENDIF
