#IFDEF SPANISH
   #define STR0001  "Sin Nombre "
   #define STR0002  "¿Desea borrar este atajo? "
   #define STR0003  "Atencion"
#ELSE
   #IFDEF ENGLISH
	   #define STR0001  "Unnamed..."
	   #define STR0002  "Delete this Short-Cut?"
	   #define STR0003  "Atention"
   #ELSE
	   #define STR0001  "Sem Nome..."
	   #define STR0002  "Deseja excluir este atalho?"
	   #define STR0003  "Aten‡Æo"
	#ENDIF		
#ENDIF