#IFDEF SPANISH
         #define STR0001  "Facturaci¢n"
         #define STR0002  "Matriz"
         #define STR0003  "T‚rmino Normal"
         #define STR0004  "Comprobando Fecha de Validez de los Lotes"
         #define STR0005  "Comprobando Lotes con Fecha de Validez Expirada ..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Invoicing"
         #define STR0002  "Headoffice"
         #define STR0003  "Normal End"
         #define STR0004  "Verifing Validity Date of Lots"
         #define STR0005  "Verifing Lots with Due Validity Date..."
   #ELSE
         #define STR0001  "SIGAPCI"
         #define STR0002  "Matriz"
         #define STR0003  "T‚rmino Normal"
         #define STR0004  "Verificando Data de Validade dos Lotes"
         #define STR0005  "Verificando Lotes com data de validade vencida ..."
   #ENDIF
#ENDIF
